### PR TITLE
gui: improve start suite --owner=USER logic

### LINKED ISSUE #2377: recent bug: gcylc launches wrong cylc version
Just noticed on current master, starting a suite from  `gcylc` when `CYLC_HOME=/home/USER/cylc.git` (e.g.) launches default installed version  `/opt/cylc` instead of the repository version.
```
~/cylc.git$ git bisect bad
b61189dd313026eb01c1706308af7f769525ae26 is the first bad commit
commit b61189dd313026eb01c1706308af7f769525ae26
...
    Improve remote host/owner logic
```

### LINKED ISSUE #2399: Job host init not done for other-user-same-host (recent bug)
Broken since last release (7.4.0) probably by #2358 ?

### PR DESCRIPTION
**Pull request by matthewrmshin**
And:
* Improve `--host=HOST` logic.
* Fix attempt to write None in debug mode.

Should fix #2377.

UPDATE: close #2399

### CODE REVIEW

**Comment by hjoliver** [comment]
(note #2377 is not just about the GUI, although it seemed so at first)

**Comment by matthewrmshin** [comment]
The logic in the GUI was not ideal. This should be fixed here.

(However, I don't think it is safe to pass CYLC_HOME to an alternate host, as cylc deployments may be installed in very different locations.)

**Comment by hjoliver** [comment]
> However, I don't think it is safe to pass CYLC_HOME to an alternate host...

I agree with that!  I just mean `cylc run --user=$USER` even from the CLI is now (on master) causing a remrun for user equal to $USER (i.e. not an alternate user account)

**Comment by matthewrmshin** [comment]
OK. I'll take a look at this one as well.

**Comment by hjoliver** [comment]
(previously, `--user=$USER` was presumably being identified as "not a remote/other user" and therefore not invoking a remrun)

**Comment by matthewrmshin** [comment]
Latest change should do it.

**Pull request merged**
