### PR TITLE
Subprocpool: use SpooledTemporaryFile instead of TemporaryFile [7.8.x]

### PR DESCRIPTION
**Pull request by matthewrmshin**
Back port #3018.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
(Goodness. Had to kick cylc-show/06 test 5 times before passing. I am going to back port the fix by @oliver-sanders to 7.8.x.)

**Comment by kinow** [comment]
Tell me about it. Today I spent the day kicking jobs for #3040 , #3042 , and while investigating if a fix would work for #3004. No kidding, but about 30% of my day today was kicking travis or doing other tasks with one eye on the favicon of firefox (waiting for it to turn red :angry:  ). Might have some time while other issues pending for `setup.py` get reviewed/fixed, so will try to use that time to work on de-flaking another test.

**Comment by hjoliver** [comment]
It's a mystery (and a frustrating one at that) - why our tests on T-CI suddenly seem much flakier than they were.  Free 🍺 🍻 to anyone who can solve this...

**Comment by matthewrmshin** [comment]
Conflict resolved. #3045 should help with at least one flaky test.

**Comment by kinow** [comment]
>It's a mystery (and a frustrating one at that) - why our tests on T-CI suddenly seem much flakier than they were.

Could it be that we are simply getting more pull requests? I wish Travis CI would allow us to see our activity in the past months.

**Comment by kinow** [comment]
>>I wish Travis CI would allow us to see our activity in the past months.

Closest I found: http://scribu.net/travis-stats/#cylc/cylc/master

**Pull request merged**
