### PR TITLE
fix poll timers list override issue

### PR DESCRIPTION
**Pull request by matthewrmshin**
Ensure that polling intervals lists are not overridden.

### CODE REVIEW

**Comment by hjoliver** [comment]
@matthewrmshin - can you briefly explain the bug here?

**Comment by matthewrmshin** [comment]
This is the classic case where the setting is a list and we are modifying the list in place, instead of using a copy.

**Comment by hjoliver** [comment]
Ah, got it, thanks.

**Comment by oliver-sanders** [comment]
In the future the global configuration should be readonly, see also https://github.com/cylc/cylc/issues/164

**Pull request merged**
