### PR TITLE
cylc run/restart: load suite.rc before daemonize

### LINKED ISSUE #1720: Better error message for cycle point constraints
I'm finally going through and re-implementing our cold-start tasks using the `R1` syntax, and decided to use the initial and final cycle point constraints to make sure the user won't specify an odd value.  Currently both are set to `T00,T06,T12,T18`.

However, if I run the suite with a bad startup time (i.e. `2015012503`), the suite appears to start successfully.  I have to go to the suite error log file (`cylc log -e suitename`) in order to see the traceback and the error message that "Initial cycle point 2015012503 does not meet the constraints ['T00', 'T06', 'T12', 'T18']".

These constraints are in there to make the suite more tolerant to user error - however, having the suite appear like everything is OK and then finding out it didn't start (either via `cylc mon` or even in the GUI) is a bit frustrating.  I know where to look, but I think users would be best served if errors like this were actually shown on the command line when `cylc run` is used or via a dialog box in the GUI.

Steps to reproduce:
    1. Define initial/final cycle point constraints
    2. Supply (either by command line `cylc run` or `gcylc`) an invalid cycle point constraint
    3. Watch the suite appear to start like everything's normal, then show nothing in the GUI or in `cylc mon`
    4. Go hunting for what could have gone wrong, find the answer in the suite error log

### PR DESCRIPTION
**Pull request by matthewrmshin**
This allows suite.rc errors to display on screen before suite gets
daemonized.

Close #1720.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
For some reason, I am unable to get the multi-process worker pool to work if it is started before the process is daemonized. This means that the best I can do right now is to do:
1. load `suite.rc`
2. daemonize
3. start worker pool

The problem is that by starting the worker pool after loading `suite.rc`, the child processes may end up with a bigger memory footprint.

**Comment by hjoliver** [comment]
>  the child processes may end up with a bigger memory footprint.

How much bigger?

**Comment by matthewrmshin** [comment]
> How much bigger?

Each will have the memory footprint of the loaded `suite.rc`.

**Comment by hjoliver** [comment]
Ah, I get it.

**Comment by matthewrmshin** [comment]
I'll close this down for the moment until I find a better solution.

**Pull request closed without merging**
