### PR TITLE
Add check for zero to xrandom (7.8.x backport)

### PR DESCRIPTION
**Pull request by kinow**
Backport for #3039 and #3040.

### CODE REVIEW

**Comment by dwsutherland** [comment]
See suggestion:
https://github.com/cylc/cylc/pull/3040#discussion_r268544744

**Comment by kinow** [comment]
Dropped the three commits, then cherry-picked again the three new ones from the related pull request after addressing feedback received there :+1:

**Comment by hjoliver** [comment]
> 
> 
> Dropped the three commits, then cherry-picked again the three new ones from the related pull request after addressing feedback received there 👍

Did you push your changes up?  (Still has the old version of the percent code, when I just looked).

**Comment by kinow** [comment]
Hmmm, maybe I forgot to push the changes. Trying again. Thanks for the check

**Comment by kinow** [comment]
So turns out I cherry-picked the commits of this pull request, and not the commits in the branch of the other pull request. Not happy with that, I reset the branch, start over, just to realize I've reset onto `master`, not `7.8.x`... then I reset on `7.8.x`, and cherry-pick the commits in this branch again.

Very deep sigh, then type and repeat out loud what I am doing, until I have reset on `7.8.x`, and cherry-picked the commits in the other branch.

Should be alright now @hjoliver . Phew. Not writing any important code today! Sorry.

**Comment by hjoliver** [comment]
He heh, need more coffee @kinow ? ☕️

**Comment by kinow** [comment]
Looks like! :rofl: I'm double-checking now that this will work alright with Py2. I forgot to run the doctests in this file using python2

**Comment by kinow** [comment]
One test will have to be adapted for Python2 (tested with Python3, and it is working):

```
kinow@kinow-VirtualBox:~/Development/python/workspace/cylc$ git status
On branch 7.8.x-backport-pr-3040
nothing to commit, working tree clean
kinow@kinow-VirtualBox:~/Development/python/workspace/cylc$ python2 -m doctest -v lib/cylc/xtriggers/xrandom.py
Trying:
    xrandom(0, 0)
Expecting:
    (False, {})
ok
Trying:
    import sys
Expecting nothing
ok
Trying:
    mocked_random = lambda: 0.3
Expecting nothing
ok
Trying:
    sys.modules[__name__].random = mocked_random
Expecting nothing
ok
Trying:
    xrandom(20, 0)
Expecting:
    (False, {})
ok
Trying:
    import sys
Expecting nothing
ok
Trying:
    mocked_random = lambda: 0.9
Expecting nothing
ok
Trying:
    sys.modules[__name__].random = mocked_random
Expecting nothing
ok
Trying:
    mocked_randint = lambda x, y: 1
Expecting nothing
ok
Trying:
    sys.modules[__name__].randint = mocked_randint
Expecting nothing
ok
Trying:
    xrandom(99, 0)
Expecting:
    (True, {'COLOR': 'orange', 'SIZE': 'small'})
**********************************************************************
File "lib/cylc/xtriggers/xrandom.py", line 63, in xrandom.xrandom
Failed example:
    xrandom(99, 0)
Expected:
    (True, {'COLOR': 'orange', 'SIZE': 'small'})
Got:
    (False, {})
1 items had no tests:
    xrandom
**********************************************************************
1 items had failures:
   1 of  11 in xrandom.xrandom
11 tests in 2 items.
10 passed and 1 failed.
***Test Failed*** 1 failures.
```

**Comment by kinow** [comment]
@hjoliver , in `satisfied = random() < int(percent) / 100`, the `int(99) / 100` now returns `0` with Python 2, unless one of the sides of the operation is a float, e.g. `satisfied = random() < int(percent) / float(100)`.

Updating this pull request, but I think it's alright to leave it as-is in the other branch for the new code. WDYT?

**Comment by hjoliver** [comment]
It works in both both Python 2 and 3 if the numerator is a float.  And not really any reason to insist on the denominator (100) being an integer either.

So, to avoid any confusion in our new bilingual reality, I vote for `float(percent)/100.0` in both cases.

**Comment by hjoliver** [comment]
(I should say, it works in P 2 or P 3 if *either* the numerator or the denominator or both are floats).

**Comment by dwsutherland** [comment]
> It works in both both Python 2 and 3 if the numerator is a float. And not really any reason to insist on the denominator (100) being an integer either.
> 
> So, to avoid any confusion in our new bilingual reality, I vote for `float(percent)/100.0` in both cases.

Oh I just said the same in [3040](https://github.com/cylc/cylc/pull/3040#pullrequestreview-218668485)

XD

**Comment by dwsutherland** [comment]
`float(percent) / 100` and `float(percent) / 100.0` both seem to work BTW

**Comment by kinow** [comment]
Yup, just read your comment there @dwsutherland .

@hjoliver I'm Ok with the `float(percent)`. I used `float(100)` because the percent is being cast to `int` in the method, and didn't want to re-cast to `int`. But perhaps we should allow users to define values like `1.1111`, `99.5`, etc, and just do `float(percent)` instead?

**Comment by kinow** [comment]
(I'll document the final decision on these changes in the original issue, so it doesn't get lost after the pull request, and users can reference to the original ticket in the changelog)

**Comment by dwsutherland** [comment]
> Yup, just read your comment there @dwsutherland .
> 
> @hjoliver I'm Ok with the `float(percent)`. I used `float(100)` because the percent is being cast to `int` in the method, and didn't want to re-cast to `int`. But perhaps we should allow users to define values like `1.1111`, `99.5`, etc, and just do `float(percent)` instead?

It makes sense to divide a float by an integer, but the with the result taking the numerator type (I assume), the inverse isn't doesn't. Hence why I think `Float/ 100` works in python.

**Comment by kinow** [comment]
@dwsutherland 

>It makes sense to divide a float by an integer, but with the result taking the numerator type (I assume), the inverse doesn't. Hence why I think Float/ 100 works in python.

I think `float/int` or `int/float` will produce the same result in python2. Whereas in python3 `int/int` always produce `float` (even `4/2` will give `2.0`).

What I meant before, is that even though we did no have types in the function signature, internally `percent` was treated as an `integer`. Changing it to support a value like `33.3` would actually be a change in the function signature (which I'm OK with).

**Comment by hjoliver** [comment]
> What I meant before, is that even though we did no have types in the function signature, internally percent was treated as an integer. Changing it to support a value like 33.3 would actually be a change in the function signature (which I'm OK with).

Given the rather trivial purpose of the little example trigger function, I don't think anyone will ever notice the difference in behaviour between 33% and 33.3333%!  

However, for the ultimate in purity and to avoid any future complaints, yes let's change the function signature to take a float percent value 👍 

(Sorry @kinow you'll be getting well sick of these PRs by now!!!)

**Comment by kinow** [comment]
I really expected this to be one of those easy ones haha. Updating the branches and will comment in the ticket what was discussed here. Thanks @hjoliver and @dwsutherland !

**Comment by hjoliver** [comment]
Travis failure unrelated.

**Pull request merged**
