### PR TITLE
Fix rsync syntax for remote job logs retrieval

### PR DESCRIPTION
**Pull request by matthewrmshin**
Exclude and include patterns need to be more specific. It was pulling
files from the whole of `log/job/` directory. It should now work as
intended, i.e. only pulling files from a selection.

Problem introduced by #1599. (This was discovered by running the `rose test-battery` in a specific combination of the cylc `global.rc`.)

@hjoliver @arjclark  please review.

### CODE REVIEW

**Comment by arjclark** [comment]
Looks good to me. Test battery passing in my environment with exceptions of:
```
Test Summary Report
-------------------
./tests/ext-trigger/00-satellite.t    (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  2
./tests/integer-cycling/00-satellite.t (Wstat: 0 Tests: 2 Failed: 1)
  Failed test:  2
```
which aren't working for me on master either at the moment.

**Comment by hjoliver** [comment]
@arjclark - those tests are passing for me, here and on master.  Can you double check and provide more details?

**Comment by hjoliver** [comment]
Looks good to me to, tests passing.

**Comment by arjclark** [comment]
Errors experienced here and on master seem to be timeout related:

```
2015-09-18T08:58:06+01 WARNING - suite timed out after PT40S
'Abort on suite timeout is set'
2015-09-18T08:58:06+01 WARNING - some active tasks will be orphaned
---  

+++  

@@ -1,4 +1,3 @@

-[collate.3] -triggered off ['products.3']
 [get_data.1] -triggered off ['prep.1']
 [get_data.2] -triggered off ['get_data.1']
 [get_data.3] -triggered off ['get_data.2']
'ERROR: triggering is NOT consistent with the reference log'
ERROR: Triggering check FAILED
ERROR: shutdown EVENT HANDLER FAILED
ERROR: SUITE REFERENCE TEST FAILED
```
Upping the timeout period to PT1M makes them more reliable for me.

**Pull request merged**
