### PR TITLE
7.7.2 take 1

### PR DESCRIPTION
**Pull request by matthewrmshin**
Cherry-pick from:
- #2710
- #2711
- #2714
- #2715
- #2719
- #2716
- #2721
- #2723
- #2724
- #2726
- #2728
- #2736

### CODE REVIEW

**Comment by oliver-sanders** [comment]
We may as well hold this until we've slotted in (or bumped) the 5 outstanding next maintenance issues.

**Comment by matthewrmshin** [comment]
This should be the final version. I'll kick off some tests in my normal work environment as well.

**Comment by oliver-sanders** [comment]
This has all Next Maintenance PRs except #2721, if we want to bump it to next release that's fine with me, just change the milestone.

**Comment by matthewrmshin** [comment]
#2721 and #2736 added. The is the final version after the previous final version.

**Comment by matthewrmshin** [comment]
All good in my environment.

**Comment by hjoliver** [comment]
I can make the release as soon as @oliver-sanders approves this.

**Pull request merged**
