### PR TITLE
Changes to allow grouped sub-graphs to be visible on GCylc startup.

### PR DESCRIPTION
**Pull request by jonnyhtw**
Hi there

As per [this](https://groups.google.com/forum/#!topic/cylc/RwE1q4Dxs3U) post on the Cylc Google group, here is a branch to allow GCylc to show subgraphs on start up.

Cheers

Jonny

### CODE REVIEW

**Comment by hjoliver** [comment]
@jonnyhtw - does this work as you want now?

**Comment by jonnyhtw** [comment]
Hi @hjoliver 

> does this work as you want now?

Yes it does! Thanks @oliver-sanders.

Let me know if I need to do anything regarding this.

Thanks again

Jonny

**Comment by oliver-sanders** [comment]
I Forgot about documenting the option! It would be good if we could auto-document from the `cfgspec` modules.

**Comment by hjoliver** [comment]
@jonnyhtw is probably in transit to Exeter at the moment (as I will be in about 36 hours).  No massive hurry on this though (I think I mistakenly gave him the impression that this was merged already).

@oliver-sanders - that's a good idea.  Can you post a new issue for that?  Implementation could proabably wait for the forthcoming sphinx-conversion though...

**Comment by jonnyhtw** [comment]
Hello!

I will be underway very shortly. 

I haven't contributed to the docs before so please let me know how to go about this and I'll get on it (when possible!).

Very best

Jonny ✌️

**Comment by jonnyhtw** [comment]
Thanks very much @oliver-sanders 

I've committed my first go at the docs and can come and chat to you tomorrow (Friday) about this if you are around.

Many thanks 😄 

Jonny

**Comment by oliver-sanders** [comment]
I think this should be sufficient but feel free to pop by.

**Comment by jonnyhtw** [comment]
Wahoo exciting! 🍾

**Pull request merged**
