### PR TITLE
validate, etc: search registered suites before cwd

### LINKED ISSUE #707: cylc validate: undesirable mixing of REG and PATH
If I have a registered suite name and the current directory I'm in has a directory with the same name cylc validate seems to be giving preference to the directory over the registered suite in cases where the sub-directory has a suite.rc in it.

e.g. I have registered a suite as `test` for purposes of doing a test run with it (true name irrelevant). The current directory I'm in has a suite directory in it that just happens to be called test. The one in the directory will be given precedence over the one in the database.

If nothing else, we should probably give precedence to the registered suite first. It might also be better to use a switch for purposes of using a path rather than letting the two mingle like this.

### PR DESCRIPTION
**Pull request by matthewrmshin**
E.g. `cylc validate foo` will now search for `foo` in the registration
database before the current working directory.

Close #707.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Note: I got rid of `cylc.registration.localdb.get_rcfiles` because its result is always junked.

**Comment by matthewrmshin** [comment]
@hjoliver @arjclark please review.

**Comment by hjoliver** [comment]
Review 1 - looks good, tests as working correctly.

**Comment by matthewrmshin** [comment]
@benfitzpatrick please review 2 while @arjclark is away.

**Comment by benfitzpatrick** [comment]
Looks fine.

**Pull request merged**
