### PR TITLE
cylc version now handled by bin/cylc

### LINKED ISSUE #2634: Redundant cylc version command?
You can print version number with:
```
cylc -v
cylc --version
```
These are handled by `bin/cylc`; but we also have:
```
cylc version
```
which invokeds `bin/cylc-version` and has a `--long` option to print the executable path as well.

@cylc/core - does anyone recall why we have both of these?  Presumably we consolidate them into one.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Close #2634.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@sadielbartholomew please sanity check.

**Comment by hjoliver** [comment]
Good spotting @sadielbartholomew - on checking, several other aspects of the "cylc help" documentation are now wrong (and probably have been for a while - not due to this change).

**Comment by sadielbartholomew** [comment]
I can approve if the intention is to fix those documentation issues in a future commit, though preferably they can be addressed here so they will not possibly be forgotten about / ignored due to higher priorities.

**Comment by matthewrmshin** [comment]
Updated to allow `cylc help version`.

**Pull request merged**
