### PR TITLE
Paramaterized tasks - extras

### PR DESCRIPTION
**Pull request by hjoliver**
Follow-up to #1953 

 * parameter expansion in lists of task names under `special tasks` and `queues`  

 * in the above, multi-param names have to be quoted to protect the list separator character:  
```
$ cylc val foo
ERROR: names containing commas must be quoted (e.g. 'foo<m,n>'):
   [scheduling][special tasks]exclude at start-up = model<run,mem,c>
```
 * ensure that `$CYLC_TASK_PARAM_xxx` exported first in task environments, to allow immediate use in the environment section.

 * document integer parameter padding, and how to get partial ranges.

### CODE REVIEW

**Comment by hjoliver** [comment]
@matthewrmshin - please review/assign.  Bullet points 1 and 3 above are really bugs in my initial implementation, although you can work around them by use family names under `special tasks` and only using `CYLC_TASK_PARAM_` vars in task scripts, not environment sections).

As soon as this is in I'll make the new release.

**Comment by hjoliver** [comment]
(I need to put in a few regression tests for this stuff, in addition to all the new unit tests in the parameter expansion and graph parsing modules, but this could wait for the next next-release depending on urgency).

**Comment by arjclark** [comment]
@matthewrmshin - sanity check fine, test battery ok in my environment.

**Comment by matthewrmshin** [comment]
Looks OK. Tests OK (with and without global configuration) in my environment.

**Pull request merged**
