### PR TITLE
Support suite UUID in suite/task event handlers

### LINKED ISSUE #2901: Expose suite UUID to event handlers.
This will allow external systems to identify the unique "suite run", in case a suite is started again from scratch.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Close #2901.

### CODE REVIEW

**Comment by hjoliver** [comment]
@matthewrmshin - thanks for implementing this!  Taking a look now...

**Comment by hjoliver** [comment]
(Yes, our "manager" classes have multiplied since first introduced, and have become a bit entangled.)

**Comment by matthewrmshin** [comment]
@kinow You are right about the dependency issue. (I should have known better!) I'll reimplement this change without introducing extra big dependency. (Testing in my local environment now.)

**Comment by kinow** [comment]
@matthewrmshin added more as a side note, as I think the code is really good and ready to be merged (unless you'd like to fix the comment). I only noticed the dependency because I stared (literally gawked) at the code for over 15 minutes thinking "If I had to implement it... could I do it now?"... alas I could understand how to test it after reading the tests (and I think it's related to a presentation of someone from Melbourne that needed it?) :disappointed: but eventually I will be able to implement changes like this! :tada:

**Comment by matthewrmshin** [comment]
Should all be good.

**Comment by hjoliver** [comment]
That does look cleaner!  Merging...

**Pull request merged**
