### PR TITLE
job file: time stamp xtrace on debug mode

### LINKED ISSUE #1719: job scripts: ability to have timings diagnostics
Context: We've seen some surprisingly long times for job scripts to fire off things like task messages in their trap routines but we're not sure where the time is being spent.

It would be useful to be able to turn on time stamps (or something to that effect) that would allow us to know how long it takes for various parts of the script to run.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Turn on `set -x` with a PS4 string that produces a time stamp on
verbose+debug mode.

Close #1719.

### CODE REVIEW

**Comment by hjoliver** [comment]
@matthewrmshin - do you want this reviewed yet?

**Comment by matthewrmshin** [comment]
I am struggling to see how this can be used effectively at the moment. It is a simple change that may never be used.

**Comment by matthewrmshin** [comment]
(The main problem is that we don't want users to switch on verbose mode by default, so when a problem occurs, the diagnostic will be at normal mode. The usual thing that is going to happen afterwards is that as soon as the user switches on verbose mode, the problem goes away!)

**Comment by matthewrmshin** [comment]
@hjoliver Having said that, the change should be harmless, so please feel free to review it.

**Comment by matthewrmshin** [comment]
(Branch rebased.)

**Comment by hjoliver** [comment]
@matthewrmshin - I quite like this, but I think the job file `set -x` should be turned on for debug mode alone, regardless of verbose mode.

**Comment by matthewrmshin** [comment]
`set -x` is now on for either verbose mode OR debug mode.

**Comment by hjoliver** [comment]
Matt, I was more thinking debug mode only for `set -x`, that seems more standard behaviour to me (I think of verbose mode as extra info for users who want to understand the sequence of events, and debug mode as huge amounts of outputs for those - usually developers - wanting to debug serious problems...). However, feel free to persuade me otherwise!

**Comment by matthewrmshin** [comment]
Now only debug mode.

**Comment by matthewrmshin** [comment]
@arjclark please review 2. (Note that @hjoliver has not yet approved this.)

**Comment by hjoliver** [comment]
Approved!

**Comment by arjclark** [comment]
Looks ok to me. Test battery passing in my environment.

**Pull request merged**
