### PR TITLE
Add locking around operations on settings in broadcast

### LINKED ISSUE #1539: cylc broadcast during dumping can bring down a suite
New problem seen today in our parallel suite.

It appears that while pickle dumping of the broadcast setting was occurring, a broadcast was actioned leading to an exception being thrown and the suite shutting down:

suite out:
```
Suite shutting down at 2015-07-17T10:15:03Z (ERROR: dictionary changed size during iteration)
```
suite log:
```
2015-07-17T10:15:02Z INFO - [nc_check.20150717T1015Z] -(current:submitted)> nc_check.20150717T1015Z started at 2015-07-17T10:15:02Z
2015-07-17T10:15:02Z INFO - Broadcast set:
+ [NC_HPC.20150717T1015Z] [remote]host=$(rose host-select xcf)
2015-07-17T10:15:03Z INFO - Suite shutting down at 2015-07-17T10:15:03Z (ERROR: dictionary changed size during iteration)
2015-07-17T10:15:03Z WARNING - some active tasks will be orphaned
```
suite err:
```
Traceback (most recent call last):
  File "/opt/cylc-6.4.0.u2/lib/cylc/run.py", line 75, in main
    server.run()
  File "/opt/cylc-6.4.0.u2/lib/cylc/scheduler.py", line 927, in run
    self.state_dumper.dump()
  File "/opt/cylc-6.4.0.u2/lib/cylc/suite_state_dumping.py", line 90, in dump
    wireless.dump(handle)
  File "/opt/cylc-6.4.0.u2/lib/cylc/broadcast.py", line 225, in dump
    pickle.dump(self.settings, file_)
RuntimeError: dictionary changed size during iteration
```

@benfitzpatrick found the following relevant posting via a quick google search:

http://bytes.com/topic/python/answers/467108-runtimeerror-dictionary-changed-size-during-iteration-good-atomiccopy-operations

which suggests that ultimately the problem is down to threaded access to the dictionary being dumped.

### PR DESCRIPTION
**Pull request by arjclark**
Close #1539 

Make use of locking to prevent simultaneous dumping and changing of `self.settings` in the BroadcastServer object.

@matthewrmshin - please review (I haven't broken anything as far as I can tell)

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@hjoliver please review 2.

**Comment by hjoliver** [comment]
I can't see any problems (although it is difficult to test this!).  It would be *slightly* cleaner with context manager style locking?
```
with self.lock:
    # stuff...
```

**Comment by arjclark** [comment]
@matthewrmshin - I seem to remember our discussing using "with" and deciding not to use it. Can you comment?

**Comment by arjclark** [comment]
Apparently we'd had some concerns about with and whether it was guaranteed to release the lock. @matthewrmshin is satisfied this will work ok so I'll convert the `try ... finally`s to `with`s

**Comment by arjclark** [comment]
@hjoliver - converted as suggested. Test battery still seems fine my end.

**Comment by benfitzpatrick** [comment]
Missing a lock around `_prune`, which is called outside the lock in `clear`

**Comment by arjclark** [comment]
I'll pop up a pull request with that bit in (I think it's ok as is but better safe that sorry).

**Comment by hjoliver** [comment]
@matthewrmshin - btw, I had assumed above that you asking me to review 2 meant your review 1 was done.  Maybe I jumped the gun though?

**Comment by arjclark** [comment]
@hjoliver - @matthewrmshin is away atm. I don't think you jumped the gun there

**Pull request merged**
