### PR TITLE
gui: fix graph view family ungroup

### LINKED ISSUE #2158: GUI graph view right-click family ungroup broken since 7.0
(reported on cylc@googlegroups.com)

Causes `HTTP Error 500: Internal Server Error`.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Should fix #2158.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
I was going to add a test as well, but since I am creating an ad-hoc command for the API call, it involves modifying `lib/cylc/_init__.py` due to `lib/cylc/version.py` exiting if your executable is not in `bin/` of the cylc source tree.

The changeset is here: f4927ed5187e3814c6c586b9de5cdb6cb227badd. Any concerns?

**Comment by hjoliver** [comment]
> Any concerns?

Not that I can think of.

**Comment by matthewrmshin** [comment]
Test added.

**Comment by hjoliver** [comment]
This appears to be double-approved - merging...

**Pull request merged**
