### PR TITLE
GUI browse URL improvements

### PR DESCRIPTION
**Pull request by hjoliver**
A user reminded me that browsing suite and task URLs from the GUI does not work if (a) the GUI is not running on the suite host account; *and* (b) the GUI account does not have non-interactive ssh access to the suite host account.  Reason: the GUI simply invokes the `cylc doc` / `cylc browse` command, which parses the suite definition - which can't be done from a remote account with no non-interactive ssh access to the suite host account.

Main change in this PR:
 * store suite and task URLs in the daemon state summary, for use by the GUI

Also:
 * allow use of string templates to replace suite and task names in URLs (was our old-style pseudo environment variable syntax, retained as well for back-compatibility) 
 * tidy some associated GUI code a little
 * User Guide: document exact requirements for remote access to suite-parsing and file-retrieval commands, including via the GUI; and clarify the same for suite client commands

### CODE REVIEW

**Comment by hjoliver** [comment]
@matthewrmshin - in light of recent emails - I should add to the documentation on this PR, about the effect shared filesystem between GUI host and suite daemon host.  My new section on the GUI and ssh is for the non-shared case.

**Comment by matthewrmshin** [comment]
In the future, we should modify the GUI so that all relevant commands are accessed though the API of the running suite (with the exception for suites running on `$USER@localhost`?) so we don't have to rely on non-interactive SSH.

**Comment by hjoliver** [comment]
Yes and no - some of the current GUI functionality could not easily be done that way, e.g. edit the suite definition!  (But we could decide that's not what the GUI is for, I guess).  The other concern is, do we want huge suite or job logs being served up by the suite daemon?

**Comment by matthewrmshin** [comment]
Not easy, but possible. Imagine a work flow like this:
* GUI downloads the content of the `suite.rc` from suite.
* GUI starts an editor for the content.
* On change, GUI uploads the content of the file to the suite.
* Suite runs reload with the uploaded content.

On large files, I am not sure what the impact would be on the suite, but I would imagine that it is no different from how Rose Bush serves log files via cherrypy.

**Comment by hjoliver** [comment]
Fair enough, it certainly is possible.  For the future web GUI, we should either do that or drop these functions of the current GUI.

**Comment by hjoliver** [comment]
Still TO DO: https://github.com/cylc/cylc/pull/2449#issuecomment-337167267

**Comment by hjoliver** [comment]
Updated docs for the shared filesystem case, added some doc strings, and rebased to master. Hopefully this is good to go now.

**Pull request merged**
