### PR TITLE
Add CRITICAL event handler.

### PR DESCRIPTION
**Pull request by hjoliver**
(separated from #2298)

### CODE REVIEW

**Comment by hjoliver** [comment]
From the original issue https://github.com/cylc/cylc/pull/2298#issuecomment-303048597

@matthewrmshin wrote:
> If we have configured a failed handler and a critical handler, I guess both will run?

Yes, as implemented, critical handlers get all CRITICAL events.  This seems logical to me, but obviously failed handlers will get many/most of the same events.  This isn't necessarily a bad thing as critical and failed handlers could do different things.  Alternatively we could pass only non-failure CRITICAL events to critical handlers.  Or allow both options?

**Comment by matthewrmshin** [comment]
Let's go with the simple implementation unless people scream.

**Comment by hjoliver** [comment]
Ah, which is "the simple implementation" in your opinion?  (as it is now?)

**Comment by matthewrmshin** [comment]
As implemented is good enough unless people scream.

**Comment by hjoliver** [comment]
OK, glad you agree :grin:  I'll just add a test...

**Comment by hjoliver** [comment]
(actually, I already added this to the existing test).

**Comment by hjoliver** [comment]
@matthewrmshin - please assign a second reviewer.

**Pull request merged**
