### PR TITLE
Fix old site redirects to the new site

### PR DESCRIPTION
**Pull request by kinow**
I saw a comment by @sadielbartholomew last week I think, in another ticket noting that the documentation link was now broken after the move to the new site (https://github.com/cylc/cylc-admin/issues/7).

Had a look today, and found [jekyll-redirect-from](https://github.com/jekyll/jekyll-redirect-from) from Jekyll documentation, but that is useful only for redirects within the same site/repository. Not our case.

I think the current solution (i.e. instruct the browser to redirect via simple HTML) is the way to go. But if we added that HTML redirect for each page, then we would have every page of the old site redirecting to the new site.

WDYT @hjoliver ? Or is it better to leave it empty so that users are not confused as their old bookmarks would still be working? Or - yet - perhaps add only the link to docs?

Happy to close if not necessary. This is a draft pull request (IOW cannot be merged), as I haven't tested it yet (will do tomorrow morning if others think this is a good idea).

Cheers
Bruno

### CODE REVIEW

**Comment by kinow** [comment]
And just in case I need to do that again, here's the step-by-step I saved in a notepad on the desktop in case I abandoned the Sunday fun project for another day.

- added back old site generated with `jekyll build` from `cylc.github.io`
- deleted all non HTML files with `find . -type f -not -path '*/\.*' -not -name "*.html" -exec rm {} \;`
- deleted all empty folders with `find . -type d -not -path '*/\.*' -empty -exec rm -rf {} \;`
- created `/tmp/template.html` with more or less the current `index.html` contents (added [canonical form for the search engines/SEO](https://yoast.com/rel-canonical/))

```
<html>
<head>
  <meta http-equiv='refresh' content='0; URL=https://cylc.github.io/${destination}'>
  <link rel="canonical" href="https://cylc.github.io/${destination}" />
</head>
</html>
```

- replaced the content of each HTML with the template using the correct destination with `for file in `find . -type f -not -path '*/\.*' -name '*.html'`; do sed -e "s|\${destination}|${file:2}|" /tmp/template.html > ${file} ; done`
```

**Comment by kinow** [comment]
>

Actually just managed to quickly test it with my kinow.github.io repository. It is deployed there right now. Copy any URL from cylc.github.io, and paste the URL path there, and you should be redirected to Cylc's new site.

e.g. https://kinow.github.io/documentation.html redirects to https://cylc.github.io/documentation.html

Anchor links are lost, so https://kinow.github.io/documentation.html#create-a-new-suite also takes you to https://cylc.github.io/documentation.html, but that's good enough I think?

Cheers
Bruno

**Comment by hjoliver** [comment]
@kinow - this looks nice, but I imagine the main problem is links directly into pages of the HTML user guide (or is it just the handful of main site pages @wxtim?) - which is presumably a bit more of a hassle to fix (one redirect page for every pages of the multi-page user guide?).  Personally I'm not too bothered about breaking a few external links into our site - the same thing can potentially happen any time the User Guide gets updated after all - but maybe I should be bothered...

**Comment by kinow** [comment]
I think it depends on how long we will take to roll the change. `cylc documentation` is broken for me right now, and searching _cylc documentation_ in Google and in DuckDuckGo, the first result for me is 404 (https://cylc.github.io/cylc/documentation.html).

But in a few days/weeks the seach engines drop results like these, and eventually the old ones are back at the top.

**Comment by hjoliver** [comment]
Good point @kinow - OK I guess we should redirect each of the main site pages. 

Is that enough to fix the Rose doctest problems @wxtim, or are internal User Guide URLs involved too?

**Comment by hjoliver** [comment]
Ah, OK_2 @kinow - I should have looked more carefully, it seems you have done the User Guide pages too!  (links to the old LaTeX User Guide will no doubt still be broken, but we can only go so far!).

**Comment by hjoliver** [comment]
No need for another review on this.

**Comment by hjoliver** [comment]
(Yep, works nicely!)

**Pull request merged**
