### PR TITLE
cylc gui: on suite stop, reset host and port

### LINKED ISSUE #1725: gcylc - reread the port file if suite restarts
Not sure how this went unnoticed!

### PR DESCRIPTION
**Pull request by matthewrmshin**
On suite stop, reset host and port for each pyro client.

Fix #1725. @hjoliver @kaday please review.

### CODE REVIEW

**Comment by hjoliver** [comment]
Thanks, that's got it.
Review 1 - good, no problems.

**Comment by matthewrmshin** [comment]
See also #345.

**Comment by kaday** [comment]
Test-batter failure:
tests/pep8/00-bin-lib.t
````
not ok 1 - 00-bin-lib
--- 00-bin-lib.stdout	2016-02-02 14:03:46.071364728 +0000
+++ -	2016-02-02 14:03:48.488455673 +0000
@@ -1 +0,0 @@
-/net/home/h02/kerryday/cylc.git/lib/cylc/gui/updater.py:361:50: E241 multiple spaces after ','
not ok 2 - 00-bin-lib.stdout-cmp-ok
ok 3 - 00-bin-lib.stderr-cmp-ok

    stdout and stderr stored in: /var/tmp/cylc-tests-kerryday/pep8/00-bin-lib-20160202T140340Z
Failed 2/3 subtests
```

**Comment by matthewrmshin** [comment]
Syntax fixed.

**Comment by kaday** [comment]
All happy now.

**Pull request merged**
