### PR TITLE
Obsolete cylc 5 syntax

### PR DESCRIPTION
**Pull request by benfitzpatrick**
Get rid of deprecated pre-cylc-6 suite.rc syntax and (some) CLI.

The suite.rc ISO 8601 related syntax is all now sanitised, uncontroversially. However, I've also obsoleted things like `initial cycle time` vs `initial cycle point`, and options like `-t, --tag` for broadcast and `--cycle` for suite-state that were also deprecated. Those choices make logical sense, but it would be nice to agree whether we can live with them.

I'm planning on rebasing so that the diff is viewable commit-by-commit on GitHub - there are a lot of changed test files. I'll then put it up for proper review.

### CODE REVIEW

**Comment by hjoliver** [comment]
Any thoughts on the TCI build failure here?  (just wondering if this is something we need to understand or look out for; prob not specific to this branch, I'll restart the build...):
```
== /tmp/cylc-tests-travis/cylc-insert/03-insert-old-20160922T141942Z/03-insert-old-suite-err-cmp-ok.stderr ==
0a1,18
> Exception in thread HTTPServer Thread-2:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 504, in run
>     self.__target(*self.__args, **self.__kwargs)
>   File "/home/travis/build/cylc/cylc/lib/cherrypy/process/servers.py", line 205, in _start_http_thread
>     self.httpserver.start()
>   File "/home/travis/build/cylc/cylc/lib/cherrypy/wsgiserver/wsgiserver2.py", line 1943, in start
>     raise socket.error(msg)
> error: No socket could be created -- (('0.0.0.0', 43014): [Errno 98] Address already in use)
> 
> Traceback (most recent call last):
>   File "/home/travis/build/cylc/cylc/lib/cylc/network/https/daemon.py", line 156, in _ws_init
>     cherrypy.engine.start()
>   File "/home/travis/build/cylc/cylc/lib/cherrypy/process/wspbus.py", line 256, in start
>     raise e_info
> ChannelFailures: error("No socket could be created -- (('0.0.0.0', 43014): [Errno 98] Address already in use)",)
```

**Comment by hjoliver** [comment]
> I'm planning on rebasing so that the diff is viewable commit-by-commit on GitHub - there are a lot of changed test files. I'll then put it up for proper review.

@benfitzpatrick - is this still the plan or do you need one of us to take this over?

**Comment by benfitzpatrick** [comment]
Sorry for the huge delay :frowning: 

> I'm planning on rebasing so that the diff is viewable commit-by-commit

That was done, but I've just rebased again to resolve the conflicts and pushed that up.

> Any thoughts on the TCI build failure here?

It's really not meant to do that! There is a race condition in grabbing sockets when multiple cylc suites are started at once.

I deprecated 'sequential', but that was an iffy judgement call.

**Comment by arjclark** [comment]
> I deprecated 'sequential', but that was an iffy judgement call.

I have a feeling sequential is still in use in a number of places (17/20 non-PP PS38 suites are using this)

**Comment by hjoliver** [comment]
> There is a race condition in grabbing sockets when multiple cylc suites are started at once.

Is this specific to the new comms layer, and do we need to address the problem somehow?

**Comment by hjoliver** [comment]
I think we need to un-deprecate `sequential` - it's used quite a lot around here too.

**Comment by hjoliver** [comment]
@benfitzpatrick - any reason we shouldn't get this branch merged now?  It looks pretty good to me, and the conflicts are small.  Do you need @arjclark or me to take over the branch and do the honours?

**Comment by benfitzpatrick** [comment]
That would be great - thanks Hilary.

**Comment by benfitzpatrick** [comment]
> There is a race condition in grabbing sockets when multiple cylc suites are started at once.

I had tried to address this (see the code below), and I think it only happens under test-battery-like conditions. The only thing I can think of right now is that it might be better if ports were grabbed in a random shuffled order rather than sequential.

https://github.com/cylc/cylc/blob/1541791/lib/cylc/network/https/daemon.py#L145-L169

**Comment by arjclark** [comment]
@hjoliver - I've been nominated to take this branch over.

**Comment by arjclark** [comment]
> I had tried to address this (see the code below), and I think it only happens under test-battery-like conditions. The only thing I can think of right now is that it might be better if ports were grabbed in a random shuffled order rather than sequential.

#2062 raised to do this.

**Comment by arjclark** [comment]
Superseded by #2063

**Pull request closed without merging**
