### PR TITLE
Make UTC mode True by default.

### PR DESCRIPTION
**Pull request by arjclark**
So, pretty much all our suites end up having the line `UTC mode = true` put in them (I'm actually yet to see one where it isn't). Rather than have every suite have to have this line and/or rely on a site config that sets this to default for everyone there (at which point a suite will need the `mode = true` putting in anyway if it is to be shared with someone running on a different site where it isn't necessarily configured that way centrally) its probably best to just make it the default once and for all.

@cylc/core - flagging this up in case there are any objections to this (I know we've discussed doing this in past).

### CODE REVIEW

**Comment by arjclark** [comment]
N.B. if this was an issue for a particular site the site config there can be set to have `UTC mode = false` in it.

**Comment by matthewrmshin** [comment]
Hi @hjoliver I think I am not the best person to approve this as I am very biased towards running everything under UTC. If you think our international friends and partners are OK with this, then please go ahead.

**Comment by arjclark** [comment]
@matthewrmshin - have fixed the broken tests (19-restart seems flakey).

**Comment by hjoliver** [comment]
Hmmm, I'm not sure about this!  Two reasons:

 * Couldn't it be argued that any time-dependent program should use the system time supplied by the host computer by default?  No one would expect UTC to be the default for `date`, for instance.

 * I have no real evidence for this but I would guess that users (if they thought about it at least) would rather see job event times etc. in local time unless forced to use UTC because their suites depend on real time meteorological observations - which does not include climate and historical NWP case study suites for example - because otherwise a mildly difficult translation (e.g. 13 hours earlier) is needed to figure out when things happened relative to daily events: *did X happen in the suite before or after I did a reload  after morning tea yesterday?*

**Comment by hjoliver** [comment]
How about making UTC mode site-configurable, as a compromise?

**Comment by arjclark** [comment]
> How about making UTC mode site-configurable, as a compromise?

We've been able to do this since 2015 as of #1501 but we don't tend to use it as reliance on a site-specific setting would mean our suites are not necessarily shareable/portable.

**Comment by hjoliver** [comment]
Ah yes, I forgot we can already configure UTC mode centrally.  I know that doesn't entirely solve the portability problem, but it does make it easier - collaborating NWP sites could make a mutual decision to to configure UTC mode as the global default.  But even if they don't, having "UTC mode = True" in most NWP suites doesn't seem too much of an imposition to me, and I'm not very keen on making it the universal default for the reasons above - do you have any good arguments against those?

**Comment by arjclark** [comment]
Awaiting comment on here from @dpmatthews

**Comment by dpmatthews** [comment]
I'm not sure about this either. However, the trouble is that our standard advice is to put "UTC mode= True" in all suites and so, naturally, users ask why this can't be the default.

Making it our site default isn't good enough since we want our suites to work at other sites.

We could change the advice to only set UTC mode for clock triggered suites. 
However, even some historical suites include clock triggers so that they also work in real time.
Also, we don't really want all the event times, etc, being reported differently in clock triggered suites.

Is part of the problem that setting UTC mode affects all the event times, etc as well as the clock triggers? Should we just make it affect the clock triggers (or have a separate setting for this which defaults to UTC)?

Also, it occurs to be that using local time for clock triggered tasks could be confusing. For example, think about what happens with "foo[-PT1H] => foo" when the hour changes (it's often a good idea to set UTC in cron jobs for similar reasons).

**Comment by hjoliver** [comment]
> Is part of the problem that setting UTC mode affects all the event times, etc as well as the clock triggers? 

Yes, it currently affects everything including the logged event times.

> Should we just make it affect the clock triggers (or have a separate setting for this which defaults to UTC)?

That's not a bad idea.

> Also, it occurs to be that using local time for clock triggered tasks could be confusing.

That's a good point, which we could to argue that a UTC default is a good idea (at least for clock triggered suites).

But, wouldn't it seem odd to have a suite suddenly start using UTC mode if you add a clock-triggered task to it?

Just to complicate matters a bit more: #2151

**Comment by hjoliver** [comment]
Actually, I think the main problem with UTC mode is that log message timestamps make more sense in local time.  So maybe we should default to UTC for clock-triggers, but default to local time for logging events.  Or is that just madness?

**Comment by matthewrmshin** [comment]
> Or is that just madness?

I think it will become a bit chaotic. Even for non-clock-trigger suites, you may be doing some kind of case studies that require the cycles to be UTC (so you get the correct input files).

And while it is easy to have `TZ=UTC` as a blanket setting that affects everything, it is quite hard to have this applied to something but not others - it is not impossible, but will require work.

**Comment by dpmatthews** [comment]
I'd like to do a bit of testing to better understand some of the implications of these settings before I comment further. In particular I wasn't aware of `[cylc] cycle point time zone`.

**Comment by matthewrmshin** [comment]
Superseded by #2324.

**Pull request closed without merging**
