### PR TITLE
Custom message event handlers.

### PR DESCRIPTION
**Pull request by hjoliver**
This adds event handling for ~~general non-output~~ all CUSTOM priority messages.

Use case: in a system of distributed suites held together by a message broker, it would be nice to use event handlers to post messages such as "dataset xyz is ready" so that downstream consumers don't need to know the identity of the producer suite and task.  Multiple such messages might need to be emitted as a task runs.

### CODE REVIEW

**Comment by hjoliver** [comment]
Example:

```

scheduling]
   [[dependencies]]
      graph = foo
[runtime]
   [[root]]
      [[[events]]]
          custom handler = echo !!CUSTOM!! %(name)s.%(point)s %(task-priority)s %(message)s
   [[foo]]
      script = cylc message "my data is ready"
      [[[meta]]]
          task-priority = HIGH
```

Run this, and the activity log shows:
```
$ cylc cat-log -a custom-handler foo.1
[jobs-submit ret_code] 0
[jobs-submit out] 2017-08-24T22:07:38+12|1/foo/01|0|7836
2017-08-24T22:07:38+12 [STDOUT] 7836
[(('event-handler-00', 'custom'), 1) cmd] echo !!CUSTOM!! foo.1 HIGH 'my data is ready'
[(('event-handler-00', 'custom'), 1) ret_code] 0
[(('event-handler-00', 'custom'), 1) out] !!CUSTOM!! foo.1 HIGH my data is ready
```

**Comment by hjoliver** [comment]
@cylc/core - I'll document and add tests if we agree this is a good thing.

**Comment by hjoliver** [comment]
As implemented the new handler is invoked only by "unhandled messages", i.e. not by standard output messages (started, succeeded, etc.) - which is definitely the right thing to do - but also not by registered custom output messages that other tasks can trigger off of - which may not be the right thing to do. 

So, question: should custom output messages also be passed to these new event handlers?  Or should there also be a new "output handler" for those (which could be assigned the same script as "custom handler" if desired)?

**Comment by hjoliver** [comment]
(This breaks the current get-config test for obvious reasons - it adds a new suite config item)

**Comment by matthewrmshin** [comment]
I believe the neatest way to support event handlers for registered custom outputs would be to allow a free hand `<registered-output-name> handler` setting, and for the `handler events` setting to accept the name of any registered output.

**Comment by hjoliver** [comment]
@matthewrmshin that's not a bad idea, but I thought of something simpler.  Registered outputs and non-output messages are both just messages reported with `cylc message "the quick brown fox"`.  We probably don't want *all* messages (whether output or not) to go to an event handler, and the suite should now which is which.  So I just added a new message priority `CUSTOM` that singles out messages that can be passed on to a `custom handler`, whether they happen also to be registered output messages or not:

```
cylc message -p CUSTOM "the quick brown fox"
```

Tests added already.  I'll document to finish off if others agree.

**Comment by hjoliver** [comment]
Matt, revisiting your suggestion above: it would allow specific output messages to trigger specific event handlers, vs what I've implemented which is, all CUSTOM priority messages go to a single custom event handler.  I think the latter is (a) a better fit with the general philosophy of event handling - a whole class of events triggers a single handler that can make internal decisions according to the detail of the event; and (b) it allows custom handling of non-output messages - which is better because task outputs are really intended for task triggering.

**Comment by hjoliver** [comment]
(rebased onto master and added some documentation; the only code change since Matt's review is to print custom priority messages to stdout rather than stderr).

**Pull request merged**
