### PR TITLE
WIP Make cylc a module

### PR DESCRIPTION
**Pull request by kinow**
I created this branch some months ago, while in parallel started bothering the maintainers of `isodatetime` to include the `setup.py` file over there :grimacing: Showed it to @hjoliver some days ago, but it was a huge mess of commits (you know, the ol' break here, fix over there kind of commits).

After #1337, I thought it would be useful to open at least an WIP pull request so others could have a look at an example of a working `setup.py` for Cylc.

At the moment it is producing an egg file for Cylc with `setuptools` + `distutils` + some Python witchcraft.

```bash
$ python setup.py develop --user 
$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cylc.version
>>> print(cylc.version.CYLC_VERSION)
7.7.1-310-g17393
>>> 
```

### CODE REVIEW

**Comment by kinow** [comment]
This is still a work-in-progress branch, mainly waiting for:

* `isodatetime` release, so that the dependency to a git commit can be removed, and instead point to a tag
* another pull request to fix the compatibility issues with the new version of `isodatetime`. That is done in this branch in a [single commit](https://github.com/kinow/cylc/commit/ba409d45a4273d9c9c6a35748ac7cda8d006918b) to this branch, which will be deleted (i.e. `git rebase -i HEAD~4` and then mark that as dropped)
* dependency groups are added, reflecting the modular design approach in #1337 
* final round of checks, also confirming if there's any work that could be done for packaging for Conda, RPM, Deb, tar.gz, etc.
* documentation

**Comment by kinow** [comment]
I started this more because I wanted to play with Cylc's API in Jupyter Notebooks (which I think maybe would interest @jonnyhtw too?). Here's one example which I maintain using the branch in this pull request (though one of the notebooks dates a few years ago I think):

https://github.com/kinow/cylc-notebooks

**Comment by kinow** [comment]
Did not want to put any pressure on that @matthewrmshin, sorry. I will have another look at that pull request during next week, but my hopes are not too high for finding a solution that doesn't break anything else.

I was thinking about discussing the `setup.py` file with others in Melbourne, to see if that sounded like a good idea, and if we could start experimenting with it... but I was planning on bothering you guys more with coverage first, once the release is out :grimacing: :grin: 

Just raised this pull request to provide some example for the recent issue about packaging cylc. So feel free to focus on the Cylc release if you prefer, and leave the `isodatetime` for whenever you guys are ready to release :+1:

**Comment by jonnyhtw** [comment]
Hi there

Definitely interested in Jupyter integration. I'm a big fan!

Cheers

J

**Comment by kinow** [comment]
Included a few more commits (will squash/edit later) to 

- use PyTest from `setup.py` (e.g. `python setup.py test`)
- include files that are not just Python files, like the static files for Cylc Review
- simplify dependency management by listing everything in `setup.py` only
- added dependency groups, for `[ssl]`, which includes dependencies necessary to support SSL in cylc, and `[empy]`, as per name. Also included group `[all]` which is just the sum of both previous groups... it can be tested with `pip install -e .[all]`

Still a few more loose ends. Rebased onto master.

**Comment by kinow** [comment]
Note: Conda docs mention a way to upload via `setup.py`, but that generates a `PYPI` artifact, installed via `pip` and specifying the Conda PYPI repository. If we want to have a `conda install cylc`, then we need the `meta.yml`.

Had a go at uploading to Conda via PYPI and then realized it wouldn't resolve dependencies via `conda`.

via-pypi

Next week will finish experimenting with Conda, and hopefully have a `meta.yaml` for Cylc to include in this pull request.

**Comment by kinow** [comment]
Good primer on Python packaging: [A tour on Python Packaging, Nick Mavrakis](https://manikos.github.io/a-tour-on-python-packaging)

**Comment by kinow** [comment]
Finished the tests on Conda, using that small Python utility as test experiment.

## Notes:

- PCCORA had one runtime dependency, `construct`, so I thought it would be super simple to upload it to Conda.... but turns out the maintainer of `construct` never uploaded it there... instead, two developers did so, but when uploading it, they used Python 2.7...
- PCCORA required Python 3.3+, so Conda was unable to satisfy construct + Python 3.6. Looking around, found that others suggest to upload it to your own channel when that happens :disappointed_relieved: 

```bash
conda skeleton pypi construct
anaconda upload /home/kinow/Development/python/anaconda3/conda-bld/linux-64/construct-2.5.1-py37_0.tar.bz2

...
Upload complete

conda package located at:
https://anaconda.org/kinow/construct
```

After doing that, I had to include my own channel in the list of default channels, so that `conda build` for PCCORA would work too...

```
# file ~/.condarc
channels:
  - conda-forge
  - defaults
  - travis
  - kinow
anaconda_upload: false
```

- We could create a new organisation in Anaconda, say, Cylc for example. That way users could use `conda install -c cylc cylc`
- The `conda skeleton` is useful, but it doesn't work exactly like `setup.py`. For example, I can't use PYPI dependencies in the `meta.yaml` generated, they have to be duplicated, both in `setup.py` and in the generated `meta.yaml`
- I had to manually include `six` library, and `pytest-runner`. The latter is a special dependency for `setup.py`, not automatically identified by `conda skeleton`, and `six`... well, that was just weird
- It defaults to using the PYPI `.tar.gz` file + sha256... instead, I used a Git repo + Git tag... that way I can close the tag and use the tag to upload both PYPI and Conda artefacts, without having to commit any more changes

## Building the library and uploading it

After that, it finally worked to build and upload it (it does both by default, by I disabled that in my `.condarc` file.

```bash
kinow@kinow-VirtualBox:~$  conda install -c kinow pccora 
Solving environment: done

## Package Plan ##

  environment location: /home/kinow/Development/python/anaconda3

  added / updated specs: 
    - pccora


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    construct-2.5.1            |           py37_0         110 KB  kinow
    pccora-0.3                 |           py37_0        18.2 MB  kinow
    ------------------------------------------------------------
                                           Total:        18.3 MB

The following NEW packages will be INSTALLED:

    construct: 2.5.1-py37_0 kinow
    pccora:    0.3-py37_0   kinow

Proceed ([y]/n)? y


Downloading and Extracting Packages
construct-2.5.1      | 110 KB    | ######################################################################################################################################################################## | 100% 
pccora-0.3           | 18.2 MB   | ######################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
kinow@kinow-VirtualBox:~$ python
Python 3.7.0 (default, Jun 28 2018, 13:15:42) 
[GCC 7.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pccora
>>> p = pccora.PCCORAParser()
>>> p
<pccora.pccora.PCCORAParser object at 0x7f5e6a9a3a58>
>>> 
```

## Conclusion

I think it is doable to generate a `meta.yaml` for Cylc, especially if we can use the `setup.py` from this pull request. But I will push for this to happen in another ticket, as it could involve some work on the `meta.yaml` file, and also gathering feedback of others about channel name, dependencies that we need, whether all dependencies work in all environments, etc :+1:

**Comment by kinow** [comment]
The only thing holding me from removing the `WIP` from the title here now, is that it requires some changes to our tests and other files. I included a `pytest.ini` here, but this file is already included in the #2765 report test coverage PR. I would like to see it getting included there first, then drop the commits here, and it should be finally ready for review :running_man:

**Comment by hjoliver** [comment]
Test coverage reporting is now in :champagne: so ... (as per your previous comment) ... this is almost ready to go?

**Comment by hjoliver** [comment]
(I guess we need to document clearly that package installation does not address the PyGTK dependency; for that users might still need to rely on the system Python 2).

**Comment by kinow** [comment]
@hjoliver 

>(I guess we need to document clearly that package installation does not address the PyGTK dependency; for that users might still need to rely on the system Python 2).

+1

And also need to figure out what to do about the release. That's, I think, the last pending issue for me.

`isodatetime` was easier to make a package as its use was mainly as a tool. But Cylc is used as an application, and the scripts part needs more testing I think (i.e. confirm they are correctly exported to the `$PATH` of users).

Furthermore, `isodatetime`, `jinja2`, and `markupsafe` were removed. Users would have to run `python setup.py install` to grab dependencies (assuming they can download/install dependencies in their sites), or we would need to investigate the option to create a complete package.

This complete package, would be Cylc with all its dependencies included (and the `.git` folder too), so technically, it would be the same as before, and users would just have to replace the binary. We could also add this release to GitHub, so users could just go to https://github.com/cylc/cylc/releases and grab it.

**Comment by kinow** [comment]
Rebased. Pending now Travis build.

**Comment by kinow** [comment]
Blocking work on the modules, until #2918 is sorted out. Need to include the images in the package too... unless we want to go without building pygtk/pygraphviz, but instead ditching all GUI, and working only on the new module. If that's the case, #2918 can be closed, but this will be still blocked until Python3 work starts :+1:

**Comment by hjoliver** [comment]
I'll create a "blocked" label for PRs like this...

**Comment by kinow** [comment]
Good idea, thanks @hjoliver !

**Comment by hjoliver** [comment]
@kinow - did you mean to close this?

**Pull request closed without merging**
