### PR TITLE
review: fix waiting tasks

### PR DESCRIPTION
**Pull request by oliver-sanders**
#### At present waiting tasks do not appear in Cylc Review due to a SQL query error.

We were [joining](https://www.w3schools.com/sql/sql_join.asp) the tasks and jobs tables. In SQL terms `JOIN` means intersection. As waiting tasks do not have jobs they were excluded in the intersection. I've changed the `JOIN` to `LEFT JOIN` to include tasks with out jobs.

### CODE REVIEW

**Comment by oliver-sanders** [comment]
@sadielbartholomew @matthewrmshin bafa9d7 changes the approach so that waiting tasks only get displayed if requested by the user. See what you think about the approach, if you approve I'll fix the tests. Otherwise the simplest solution would just be to remove the "waiting" task state from cylc review.

**Comment by oliver-sanders** [comment]
Base changed to 7.8.x, cylc-review temporally removed on master.

**Comment by hjoliver** [comment]
(Will we remember to make the same fix later though, when `cylc review` is restored to (or for - perhaps as a separate project) master?)

**Comment by kinow** [comment]
>(Will we remember to make the same fix later though, when cylc review is restored to (or for - perhaps as a separate project) master?)

Good point! Maybe if we create a ticket, add the commit where it was removed, and a link to the branch `7.8.x`? And only destroy the `7.8.x` branch after everything has been migrated to `master`/Cylc 8?

**Comment by oliver-sanders** [comment]
> Can we change it to the one I also captured here for the job status of the submitted task

That wouldn't be appropriate as it suggests there is a job running. We could, however, just remove the job icon altogether.

**Pull request merged**
