### PR TITLE
Tidied CUG "Running Suites" section.

### LINKED ISSUE #2341: Remote suite access documentation is inadequate.
To access a suite running under another user account, the CUG currently says you just need to install the suite passphrase in the right place: https://cylc.github.io/cylc/html/single/cug-html.html#12.6.1 (and that clients will automatically retrieve and install it if you have non-interactive ssh to the suite account).

In fact, additionally:
 1. ssl.cert must be installed in the same place
 2. if you do have non-interactive ssh to the suite account, clients will also use that to get the suite port from the contat file; otherwise the `--port` option is also required (after using `cylc scan` to find the port).

### PR DESCRIPTION
**Pull request by hjoliver**
Close #2341 

(This went from correcting the remote control documentation, to a mid-size rewrite of several parts of the "Running Suites" section - and a few other bits that connect to it).

@matthewrmshin - please review and/or assign.

### CODE REVIEW

**Comment by hjoliver** [comment]
Note I'll need to change the new Remote Control section slightly depending on https://github.com/cylc/cylc/issues/2341#issuecomment-313068427 (what to do if the SSL cert is not installed); plus the suite contact file is not installed locally by clients via ssh (only the passphrase and SSL cert are) - but if manually installed the contract file is used.

**Comment by hjoliver** [comment]
This should now wait on #2344  - I'll adjust the new documentation a bit if that goes through.

**Comment by hjoliver** [comment]
TODO - document local FS access to suite contact files via #2344

**Comment by hjoliver** [comment]
Rebased and deconflicted.  Ready for review after #2344 is merged.

**Comment by matthewrmshin** [comment]
(Conflicts again.)

**Comment by hjoliver** [comment]
rebased and deconflicted.  Updated "Remote Control" section for local filesystem access to suite contact files.

**Pull request merged**
