### PR TITLE
PEP 8 compliance fixes.

### PR DESCRIPTION
**Pull request by hjoliver**
Following up #1300 with PEP 8 fixes for files touched by that pull request.  All changes are for style only.

Much helped by https://github.com/hynek/vim-python-pep8-indent.

@benfitzpatrick - please review (with apologies! ... but I suppose this needs to be done at some point)

### CODE REVIEW

**Comment by hjoliver** [comment]
(these files now pass the ```pep8``` checker).

**Comment by hjoliver** [comment]
All - can we consider doing this routinely for files touched by all new pull requests, until the whole code base is stylistically consistent?  It was a moderate pain in the ass with the main GUI app source file here but most source files are much smaller.  It's probably best to do this with style-only pull requests, to avoid muddying the waters for real changes.

**Comment by benfitzpatrick** [comment]
Looks good - but PEP8-strictly speaking, can we rename the files as well?
They should be something like `graph_updater.py` or `updater_graph.py` (better).

**Comment by hjoliver** [comment]
Will do... (I was diverted to other things today)

**Comment by hjoliver** [comment]
Filenames changes. Rebased.

**Comment by hjoliver** [comment]
(I'm not sure why git hasn't recognized ```SuiteControl.py -> app_gcylc.py``` as simply a file name change).

**Pull request merged**
