### PR TITLE
profiling: main loop profiling fix

### PR DESCRIPTION
**Pull request by oliver-sanders**
Profiling is not currently outputting a 'loop' entry every minute.

@benfitzpatrick Please Review / Reassign / Assign

### CODE REVIEW

**Comment by arjclark** [comment]
I think this change is making the supposition that the main scheduler loop takes 1 second each time through and is now dumping out profiling info every 60th loop. Strictly speaking you can't rely on this

A better solution would be to record the last dumped time and do something like:
```
if now - last_dump >= 60: #seconds
    self.log...
    last_dump = now # update last_dump time
```

**Comment by oliver-sanders** [comment]
Is it important to have output exactly every minute? My intention here was to be able to compute the average time taken per loop.

**Comment by arjclark** [comment]
Depends what you're trying to do really. If you're trying to fix it so its output for what happens in ~1 minute (of which entries can currently be missed if times don't line up) then that's not what this does - which based on your pull request title and initial comment reads as what you're trying to do. If your intention is to put out values per "N" loops then 60 is a strange number to base that on.

**Comment by benfitzpatrick** [comment]
I like Andy's suggestion - some loops can take 5 or 6 seconds in extreme suites, which would lead to a long wait for output.

**Comment by oliver-sanders** [comment]
- Have implemented the way Andy suggested but output the loop number with the memory usage.
- Also moved "end main loop" profiling line to before `raise SchedulerStop('finished')` as it wasn't being called previously.

**Comment by oliver-sanders** [comment]
@arjclark Are we happy with the new implementation?

**Comment by arjclark** [comment]
Looks sensible to me. Will get round to reviewing and testing shortly.

**Comment by arjclark** [comment]
Review 1: Looks good to me. No problems from the test battery in my environment. @benfitzpatrick - can you review 2 and make sure you're happy.

**Comment by benfitzpatrick** [comment]
I'm happy.

**Pull request merged**
