### PR TITLE
dependencies syntax: implement min(TXX, TYY) functionality

### LINKED ISSUE #1355: recurrances: run once at first instance from a set of cycles
Followup from Ben's comment in #1279 

Comment from @benfitzpatrick -

> I had been thinking about this, as I think it might be the one important thing missing at the
moment. It needs a 'minimum' feel to it. Maybe just:
>
> R/min(T00,T06,T12,T18)/PT6H

### PR DESCRIPTION
**Pull request by arjclark**
Closes #1355 

This adds the following:
 * Ability to use min(TXX, TYY) type functionality to dependency sections
 * Tests for the new functionality
 * Documentation entries

See #1355 and #1279 for details on what this is intended to do.

### CODE REVIEW

**Comment by arjclark** [comment]
@hjoliver - please review.

**Comment by hjoliver** [comment]
@arjclark - the new tests fail in my TZ.  Suite log says "Not loading foo (out of sequence bounds)".  Running in UTC mode works, but in this case I shouldn't have to do that.

**Comment by arjclark** [comment]
Hmm, worrying as I haven't used any particularly different code from elsewhere in the system to do the calculation.

**Comment by arjclark** [comment]
@hjoliver - fixed. Had been failing to account for the timezone offset in the way I was working with the entries. Changed so as to return the correct entry and process from there as normal. I've checked in a fake timezone and our local and should be ok.

**Comment by hjoliver** [comment]
@arjclark - in my timezone (+13) the new test suites still shut down immediately without running any tasks, unless ```[cylc]UTC = True``` ... which it seems to me should not be necessary??

**Comment by arjclark** [comment]
@hjoliver - testing on my end by setting and exporting TZ=NZ in my terminal and removing UTC=true from the suite.rc files indicates it should be working correctly.

Manual testing results obtained below by running from within each of the directories under tests/recurrence-min with: `cylc reg $(basename $(pwd)) .; cylc run $(basename $(pwd)) --debug; cylc unreg $(basename $(pwd))` (user path sanitized out but otherwise unchanged):

Suite | Task that runs in UTC mode (should be same)

00-basic | `foo.20100101T0600`:
```
cylc job-submit .../cylc-run/00-basic/log/job/20100101T0600+13/foo/01/job
'Finished'
Suite shutting down at 2015-03-16T21:19:26+13
DONE
```
01-offset-initial | `foo.20100101T0400`
```
cylc job-submit .../cylc-run/01-offset-initial/log/job/20100101T0400+13/foo/01/job
'Finished'
Suite shutting down at 2015-03-16T21:26:19+13
DONE
```
02-offset-truncated | `foo.20100101T0700`:
```
cylc job-submit .../cylc-run/02-offset-truncated/log/job/20100101T0700+13/foo/01/job
'Finished'
Suite shutting down at 2015-03-16T21:25:26+13
DONE
```
03-neg-offset-truncated | `foo.20100101T0400`:
```
cylc job-submit .../cylc-run/03-neg-offset-truncated/log/job/20100101T0400+13/foo/01/job
'Finished'
Suite shutting down at 2015-03-16T21:24:07+13
DONE
```
Can you check you're running with my latest version not the previous one (which I know didn't work and gave precisely the behaviour you're describing)? Maybe clear out .pyc files?

Obviously, the test battery won't work correctly without UTC=true entries due to the triggering checking, but that's expected and required in the other test suites too.

For completeness, running test battery with the above timezone setting:

```
cylc test-b tests/recurrence-min/
[INFO] cd <cylc-path>
tests/recurrence-min/03-neg-offset-truncated.t .. ok                    
tests/recurrence-min/02-offset-truncated.t ...... ok                    
tests/recurrence-min/00-basic.t ................. ok                    
tests/recurrence-min/01-offset-initial.t ........ ok
All tests successful.
Files=4, Tests=8, 23 wallclock secs ( 0.04 usr  0.01 sys +  8.68 cusr  4.00 csys = 12.73 CPU)
Result: PASS
```

**Comment by hjoliver** [comment]
@arjclark - you're right.  I was sure I had updated you're branch, but the evidence now suggests otherwise.  Apologies for the hassle :grimacing:  Anyhow, thanks, this is going to be useful.

**Comment by arjclark** [comment]
No worries, so long as its working for you :smile:

**Pull request merged**
