### PR TITLE
Broadcast: settings from file

### LINKED ISSUE #2108: broadcast: settings in file
While the `--set=[SEC]ITEM=VALUE` option to broadcast is good enough for most cases, it can be quite difficult for:
* multi-line values
* values with lots of shell meta characters.
* many values

It should be possible to support broadcast options from a file that looks like a `suite.rc` fragment (with 2 section levels removed?)

Either:

```cfg
[runtime]
    [[__BROADCAST__]]
        script = printenv FOOBAR
        [[[environment]]]
            FOOBAR=foobar
```

Or:

```cfg
# Broadcast
script = printenv FOOBAR
[environment]
    FOOBAR=foobar
```

We'll then do `cylc broadcast SUITE --file=FILE`?

### PR DESCRIPTION
**Pull request by matthewrmshin**
Close #2108.

### CODE REVIEW

**Comment by hjoliver** [comment]
Shouldn't we be able to cancel the broadcast by referring to the file too?

**Comment by hjoliver** [comment]
(Otherwise all good).

**Comment by matthewrmshin** [comment]
OK. I'll add a`--cancel-file` option.

**Comment by matthewrmshin** [comment]
`--cancel-file=FILE` option added.

**Pull request merged**
