### PR TITLE
cylc gui: preserve edges on node filter out

### LINKED ISSUE #1423: cylc gui graph view: incorrect dependency plot for offset R1 task
The following suite.rc snippet:
```ini
[scheduling]
    initial cycle point = 20140101T00
    final cycle point   = 20140104T00
    [[dependencies]]
        [[[R1]]]
            graph = "foo_cold => foo"
        [[[T00]]]
            graph = "foo[-P1D] => foo"
        [[[R1/+P2D]]]
            graph = "foo[-P1D] => reinsert_foo => foo"
```

produces an incorrect graph view in cylc gui when it first loads up:

gcylc-graph-view-delayed-r1

### PR DESCRIPTION
**Pull request by benfitzpatrick**
Currently, when a node is filtered out, the incoming
and outgoing edges from it are discarded. This can split the
graph and can mislead the user. This can be particularly bad
for runahead nodes/groups of nodes where intervening base
node cycles are filtered out.

This change replaces all connected groups of filtered-out nodes
with small placeholder special nodes.

This fixes #1423, but is more of an enhancement that's up for
critique - I'm not wedded to the display choices (scissors text, dotted lines, etc)
particularly.

It adds an extra option to cylc graph to turn on filtering for
test purposes.

The following image shows the extra functionality compared with the image in #1423:

1423_with_placeholder

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Can scissor nodes be plotted with dotted circles?

**Comment by hjoliver** [comment]
Very nice!

The new ```cylc graph``` filter option doesn't seem to work though?  If I use the node name (i.e. no cycle point) I get "node is not in graph"; if I use the full ID (with cycle point) no error, but no filtering occurs.

**Comment by benfitzpatrick** [comment]
Thanks! Maybe it could be a regex, so it wouldn't have to be a full ID?

**Comment by benfitzpatrick** [comment]
Updated with dotted node style and --filter=NODE_NAME_PATTERN.

**Comment by hjoliver** [comment]
(I'll take another look at this tomorrow; will merge it if I don't see any problems...)

**Comment by hjoliver** [comment]
Two issues:

 * I still can't get ```cylc graph --filter``` to work - nothing gets filtered out.  Presumably this is not happening for you?!
 * The gcylc graph view looks really good, although sometimes it doesn't quite produce the result I'd expect.  .e.g. on ```examples/task-states``` held after one task, with families expanded:

filtering-1
filtering-2

In the second image, shouldn't the 4 scissor nodes be combined into one?  This isn't technically wrong, I guess, it's just not an improvement on the original in this particular case...

**Comment by benfitzpatrick** [comment]
I've fixed the cylc graph GUI mode with --filter, and added something to sort that second issue.

**Comment by hjoliver** [comment]
Good.

**Pull request merged**
