### PR TITLE
Contine task event handler on restart

### LINKED ISSUE #1282: cylc stop --quick: functionality lost
It's been pointed out that we lost `--quick` functionality from cylc stop. We've tracked this back to #1117 where it snuck in.

From what I can tell, the difference between `--quick` (at cylc 5.4.14) and `--now` (cylc 6+) is that `--quick` meant event hooks still got ran but `--now` means they don't. Trying to test this is somewhat difficult as there seems to be an element of timing involved in whether you see any difference in behaviour.

As a second part, gcylc still has a "Quickly" option under "Stop Suite", which is broken.

I can't quite work out from `scheduler.py` whether task proxies with event handlers due to run will run them or not - again though it looks like a timing of the command will affect whether or not the event hooks would be run.

@hjoliver - thoughts/comments?

### PR DESCRIPTION
**Pull request by matthewrmshin**
Store task event handler try states in DB.
Load task event handler try states from DB on restart.

Close #1282. @hjoliver @arjclark please review and/or reassign.

### CODE REVIEW

**Comment by arjclark** [comment]
Looks OK to me. No problems from the test-battery in my environment. Over to you @hjoliver

**Comment by arjclark** [comment]
@matthewrmshin - I guess as this is new functionality you're only aiming this at cylc 7?

**Comment by matthewrmshin** [comment]
This is new functionality, so I don't think it justifies a back port to 6.11.x unless there is a strong demand to do so.

**Comment by matthewrmshin** [comment]
Branch rebased.

**Comment by hjoliver** [comment]
Sorry for the delay on this one, I'll review it Wednesday!

**Comment by matthewrmshin** [comment]
@hjoliver don't worry. We know you are busy.

**Pull request merged**
