### PR TITLE
cylc.rundb: task_jobs table: add primary keys

### PR DESCRIPTION
**Pull request by matthewrmshin**
Add primary keys to speed up table.

@hjoliver please review 1.
@arjclark or @kaday please review 2.

### CODE REVIEW

**Comment by hjoliver** [comment]
(Review 1) This looks fine to me.

**Comment by arjclark** [comment]
Looks ok to me. Is this something we need to worry about for backwards compatibility purposes?

**Comment by matthewrmshin** [comment]
This change should be fine for back compatible purpose.

**Comment by arjclark** [comment]
Looks ok to me. Test battery passing in my environment.

**Pull request merged**
