### PR TITLE
Happy New Year 2019!

### PR DESCRIPTION
**Pull request by hjoliver**
Super-quick sanity check please (if anyone is about)!

### CODE REVIEW

**Comment by oliver-sanders** [comment]
Missed a bit!

**Comment by kinow** [comment]
I think it missed:

- ./lib/cylc/scheduler.py (line 326, the message header printed when you run Cylc I think?)
- ./lib/cylc/gui/scanutil.py (line 377, copyright that appears in the GUI only I think?)
- ./lib/cylc/gui/app_gcylc.py (line 1218, ditto above)
- ./lib/Jinja2Filters/duration_as.py ? Not sure if necessary...
- ./tests/cylc.host_appointer/00-host-appointer.t
- ./tests/cylc-get-host-metrics/00-simple.t
- ./bin/cylc-get-host-metrics
- ./.travis/install.sh
- ./.travis/sitecustomize.py
- ./.travis/cover.py
- ./.travis/after_script.sh
- ./doc/install/html/single/cug-html.tex (line 31, I think that's the footer of the page? Also line 217)
- ./doc/install/html/single/cug-pdf.tex (line 30, the footer, and line 168)
- ./doc/install/html/multi/cug-html.tex

**Comment by hjoliver** [comment]
Thanks @kinow I'll check those now, against Oliver's set...

**Comment by kinow** [comment]
Not a problem @hjoliver , did that here, and found 

- ./doc/install/html/single/cug-html.tex
- ./doc/install/html/single/cug-pdf.tex
- ./doc/install/html/multi/cug-html.tex
- ./doc/install/html/multi/cug-pdf.tex

**Comment by hjoliver** [comment]
`doc/install` is untracked - old built User Guide.  So I think we're all good on this PR then.

**Comment by oliver-sanders** [comment]
`git clean` should sort that.

**Comment by kinow** [comment]
Oups! My mistake. `git clean` ignores those files as they are in `.gitignore`. Perhaps we can remove those entries later if we are now using sphinx only (haven't looked what happened with the PR for the new docs). Merging.

**Comment by hjoliver** [comment]
(Yes, we should update .gitignore later).  Thanks y'all's.

**Pull request merged**
