### PR TITLE
GUI: fix tree updater KeyError

### LINKED ISSUE #1564: gcylc/gsummary: KeyError point_string
screenshot_keyerror_pointstring

Error reported:
"opened cylc gsummary and this popped up when I clicked to open the" suite.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Should fix #1564 (line 402 problem).

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@kaday @arjclark please review.

**Comment by arjclark** [comment]
Looks like the correct fix. Will test later. In combination with #1611 this will close #1564.

**Comment by arjclark** [comment]
Have had a play with the gui and can't see any problems.

Over to @kaday

**Comment by matthewrmshin** [comment]
Reassign to @benfitzpatrick for review as @kaday is not available this morning.

**Comment by benfitzpatrick** [comment]
Looks fine.

**Pull request merged**
