### PR TITLE
job.sh: replace HERE document with echo commands

### PR DESCRIPTION
**Pull request by matthewrmshin**
Bash may put HERE documents in a temporary file, which is not efficient.
On older versions of Bash, it may even create temporary files under
`/tmp` instead of using `mktemp`, which can be problematic on systems
with only a small amount of space in `/tmp`.

Problem first raised by @steoxley.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
> This is probably worth a short explanatory comment so that some future developer doesn't go back the other way.

Done.

**Comment by ColemanTom** [comment]
Interesting to learn this. One question on multiple echo's. Would it be better to do an echo that spans multiple lines instead of multiple calls to echo?
```
    echo "Suite    : ${CYLC_SUITE_NAME}
    Task Job : ${CYLC_TASK_JOB} (try ${CYLC_TASK_TRY_NUMBER})
    User@Host: ${USER}@${host}
    "
```

**Comment by hjoliver** [comment]
@ColemanTom - yeah, I think that looks less clunky, but probably not worth bothering for just three lines of scripting.

**Comment by sadielbartholomew** [comment]
I'm online/working & happy to re-approve the 'single echo' approach now or very soon if you do want to change it in that way.

**Comment by hjoliver** [comment]
Actually, that scripting is now hidden from users in a shell function defined in `lib/cylc/job.sh` (sourced by job scripts) so no need to change it for three lines of `echo` with an explanatory comment above it.  If it was 10+ lines, maybe...

**Comment by matthewrmshin** [comment]
`echo` is normally a shell built-in (so very little issue performance-wise). I am not sure if it is worth grouping it into a single call with a slightly clunkier look.

**Comment by hjoliver** [comment]
(I agree, I just dislike consecutive echoes for aesthetic reasons - it looks amateurish - but as I said, for only 3 lines that aren't even visible in the job script any more, it really doesn't matter).

**Pull request merged**
