### PR TITLE
gscan: display running suites with no states

### PR DESCRIPTION
**Pull request by matthewrmshin**
This also fixes back compat with suites running at 6.4.X or below.

@hjoliver @benfitzpatrick please review.

### CODE REVIEW

**Comment by hjoliver** [comment]
Review 1 - looks fine to me.

**Comment by benfitzpatrick** [comment]
Review 2 - ditto!

**Comment by matthewrmshin** [comment]
(The main audience is suites running at 6.4.X or below. However, you can probably have an unlucky combination of a running suite with a low privacy setting, and somehow you have not access for the passphrase file.)

**Comment by benfitzpatrick** [comment]
OK

**Pull request merged**
