### PR TITLE
7.8.x patch2

### PR DESCRIPTION
**Pull request by matthewrmshin**
Back port #2945 #2976 #2988.

### CODE REVIEW

**Comment by hjoliver** [comment]
(@cylc/core - can we agree to do duplicate PRs at the time, in future, to avoid the risk of forgetting to do a combined back-port PR like this... or do you have a foolproof way keeping track of these @matthewrmshin )

**Comment by kinow** [comment]
Roger that :+1:

**Comment by sadielbartholomew** [comment]
> can we agree to do duplicate PRs at the time, in future, to avoid the risk of forgetting to do a combined back-port PR like this... or do you have a foolproof way keeping track of these @matthewrmshin

Sorry to jump in with a comment directed to Matt, but I am thinking that, despite best intentions given how busy we all are, it is easy to foresee occasions where we might forget to put up the duplicate PR. So setting up some sort of reminder, at least if there are no better ideas, would be sensible.

To do this we could use a [webhook](https://developer.github.com/webhooks/) to trigger off the event of someone pushing to the ``master`` branch, emailing them (or adding an automated comment to the PR, but that would become rather spammy) to ask them to consider whether the PR in question should be back ported. Since both the PR author & reviewing merger strictly "push" to ``master``, there will be two people notified, so that should catch most instances requiring the back port even if someone overlooked their email.

This suggestion may be overkill, but it is a possible solution.

Another would be to nominate a "back port rep" so to speak, being someone to keep an eye on all merges to ``master`` & ensure everything necessary is registered to be, and eventually gets, back ported. If there are no volunteers we can always assign the responsibility & re-allocate every so often so we all take a turn. Matt seems to have kindly took on this job so far, so it seems courteous to him if we pass on the baton?

**Comment by hjoliver** [comment]
I should have said first, thanks to Matt for doing this so far, given that he never officially volunteered for the job. 

I'm not too keen on the commit-hook idea as the vast majority of commits to master will soon be for cylc-8 and should not require back-porting.  But a few will!

Maybe all reviewers should just keep this in mind, and *request a back-port PR if one is necessary and hasn't been done yet - and don't approve the original PR until both are up?*

The back-port one is generally pretty easy and could even be done by someone else (because most of these should just be small bug fixes).

**Comment by hjoliver** [comment]
Or at the very least, put up an issue for the back-port and assign it to the next-release milestone.  Then we can't forget it.  This could be done by the PR author or a reviewer.

**Comment by matthewrmshin** [comment]
The current arrangement is OK - and it helps me keep track of the release. It is a manual process that involves me interpreting the logs and the PRs - and making some judgement on what should be back ported. Not the best process, but it is not something that takes long to do.

**Comment by matthewrmshin** [comment]
(And if we agree that PRs that should be back ported would have separate duplicated back port PRs, then we should not have more of this.)

Please aim to get this merged soon - given that the original changes were already merged to master - we should aim to only pick out any glaring Python 2 compat issues on this back port.

**Comment by hjoliver** [comment]
> (And if we agree that PRs that should be back ported would have separate duplicated back port PRs, then we should not have more of this.)

I certainly agree we should have this (as you've no doubt noticed, above :-).

Mulling over the options again, my preference is to make it part of the PR review working process.  For every PR, the reviewer should think: does this change need back porting to 7.8.x. If it does, request that either a back-port PR is done or a back-port issue raised to next-release, before giving approval. Then we can't forget.  Bingo 💥

**Pull request merged**
