### PR TITLE
rundb: dump out db operations queue on failure

### PR DESCRIPTION
**Pull request by arjclark**
This looks to implement some of the ideas raised by @hjoliver in #1213, in particular:

> * instead of aborting with uncommitted updates [to the private db], could we first write those commits to a special recovery db, and then issue instructions on how to unlock the private db (i.e. find the errant process with fuser and kill it?); and how to update the the private db from the recovery one (or could we do that automatically on restart?)

and

> * even though the missing information exists in the private db, we might still want to write a special recovery db because an external process (e.g. a resync utility) could bring down the suite by reading the private db. Options might include:

This should ensure that if a database becomes locked all pending commits/updates to it are backed up and run on restarting the suite.

I've taken the approach of creating a dictionary object and pickling that - ultimately simpler than the backup database option.

### CODE REVIEW

**Comment by arjclark** [comment]
@hjoliver - not ready for merge yet, but I thought it'd be good to get a second pair of eyes on this. I've been testing with Dave's read_lock code and been able to shutdown and (once read_lock's been stopped) restart suites.

I'll look to address the issue with allowing the external db to fail and have the suite carry on as a separate pull request. This one is primarily for the generic problem of locking that could result in either database becoming locked and losing its queued operations. Thoughts?

**Comment by hjoliver** [comment]
Looks good, I can't see any problems.

**Comment by arjclark** [comment]
@hjoliver - ready for review. Hasn't broken the test battery. Can you test manually with a suite on your end using Dave's read_lock code - 

 * Start suite
 * Run read_lock against one or more of its databases
 * Wait for the suite to fail due to database locked error
 * Check the dump file has been created
 * Stop read_lock
 * Restart suite - should load in the recorded entries

**Comment by hjoliver** [comment]
@arjclark - looks good. The only thing I've noticed is restarting a suite without unlocking a public db first works ok (it will fail and dump again soon, of course) but not the private db - in that case the suite daemon ends up running but never reaches a responsive state.  I'm not sure what causes this difference in behaviour as the two dbs are created at the same time, no?  Anyhow, might it be sensible to abort immediately on restart if a db dump is present and the db is found to still be locked?

Also, a four task test suite results in a 3.5k line pickle file containing about 130 items.  Do you foresee any problems with plain pickle files for very large suites (maybe you've tested this?)?

**Comment by arjclark** [comment]
> The only thing I've noticed is restarting a suite without unlocking a public db first works ok (it will fail and dump again soon, of course) but not the private db - in that case the suite daemon ends up running but never reaches a responsive state. I'm not sure what causes this difference in behaviour as the two dbs are created at the same time, no?

That's odd, as it's the same code for both. Will try to get to the bottom of that.

> Anyhow, might it be sensible to abort immediately on restart if a db dump is present and the db is found to still be locked?

Will see what I can do - is it possible to check for a lock without trying to add to/update the db?

> Also, a four task test suite results in a 3.5k line pickle file containing about 130 items. Do you foresee any problems with plain pickle files for very large suites (maybe you've tested this?)?

The size will relate to the number of queued up db events rather than the size of the suite so e.g. a large family of tasks running at the same time could have as many entries as a rapidly cycling suite. I'll try a few more evil test suites and see what the damage is.

**Comment by arjclark** [comment]
@hjoliver re:

> The only thing I've noticed is restarting a suite without unlocking a public db first works ok (it will fail and dump again soon, of course) but not the private db - in that case the suite daemon ends up running but never reaches a responsive state. I'm not sure what causes this difference in behaviour as the two dbs are created at the same time, no?

This seems to be as a result of the point at which the database interactions occur. In the main loop the database exceptions are handled correctly and the suite exits accordingly. On the restart *only* the primary db is accessed (hence the difference between it and the public one). It looks like it's correctly throwing an exception but is either not being looked at at that stage in things or the exception isn't being caught and dealt with (had problems with this originally with the main suite loop).

**Comment by hjoliver** [comment]
> Will see what I can do - is it possible to check for a lock without trying to add to/update the db?

A bit of googling suggests there is no way to check for a lock without attempting to write to the db (which seems a bit deficient to me!).

E.g. from http://stackoverflow.com/questions/4153091/sqlite-check-reader-writer-lock?answertab=active#tab-top

*I understand from the documentation that any function you call that tries to write to this locked database will simply return SQLITE_BUSY, and that will be your notification that the database is locked.*

If that's the case, maybe we could add a little dummy table in the db, not used for anything except write-attempts in order to check for a lock?

**Comment by arjclark** [comment]
> If that's the case, maybe we could add a little dummy table in the db, not used for anything except write-attempts in order to check for a lock?

Great minds think alike - that was the best idea I could come up with in lieu of anything better. Glad you couldn't find anything better either.

**Comment by arjclark** [comment]
@hjoliver - changed so now will check for a lock on restart and quit accordingly.

To check for locks I've gone for trying to create a temporary database. The create will fail if a lock is present.

> Also, a four task test suite results in a 3.5k line pickle file containing about 130 items. Do you foresee any problems with plain pickle files for very large suites (maybe you've tested this?)?
>> The size will relate to the number of queued up db events rather than the size of the suite so e.g. a large family of tasks running at the same time could have as many entries as a rapidly cycling suite. I'll try a few more evil test suites and see what the damage is.

I've tested with the busy suite (under dev suites) with results as follows:

 * 186K size cylc_db_dump.p file
 * 18853 lines
 * Successfully loaded in 626 "items", minor delay visible while reload was occurring

I think that's probably fine and about as bad as I can conceive for busyness of a suite.

See what you think.

**Comment by hjoliver** [comment]
>  I've gone for trying to create a temporary database.

Temporary *table*, I assume.

Looks good, I'll test it tomorrow.  Where's the exception caught, if locked (daemon top level?)?

**Comment by arjclark** [comment]
> Temporary table, I assume.

D'oh, yes, sorry!

>  Where's the exception caught, if locked (daemon top level?)?

Because of the way I've done it the exception is caught by the daemon top level as a result of the call to configure_suite under scheduler.py (ultimately by the code in run.py when it calls server.configure()).

**Comment by hjoliver** [comment]
Nice.

**Pull request merged**
