### PR TITLE
Rename command scripting etc.

### LINKED ISSUE #1384: Deprecate "command scripting" to "script" or "scripting"?
The term "command scripting" annoys me.  Primarily, the word "command" is unnecessary.  Secondarily (and much less annoyingly) the word "scripting" was originally chosen to imply a piece of the job script, not an entire script in itself, but just "script" would probably do (especially as it is often just used to invoke an external script).

So: @matthewrmshin et. al. - would you agree to the following changes, possibly with ```ing``` appended to each? (deprecations, of course, so it won't break anything):
 * ```command scripting``` to ```script```
 * ```pre-command scripting``` to ```pre-script```
 * ```post-command scripting``` to ```post-script```
 * ```environment scripting``` to ```env-script```
 * ```initial scripting``` to ```init-script```

### PR DESCRIPTION
**Pull request by hjoliver**
Close #1384 

This touched a lot of files, but it's all pretty trivial.  Worth it for slightly cleaner-looking suite definitions  :grimacing: 

Test battery passes. 

@matthewrmshin - please review or reassign.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@hjoliver Do you really want this for the next release?

**Comment by hjoliver** [comment]
> Do you really want this for the next release?

I used the new syntax in a talk recently, so I didn't want it to look as if I was lying :smile: ... but no, it's not critical of course.

**Comment by hjoliver** [comment]
Branch rebased onto master.

**Comment by arjclark** [comment]
@hjoliver - I'm not sure I'm keen on a major deprecation of key chunks of the suite.rc runtime going in to a minor release. To my mind this seems more of a Cylc 7 type change. Can we hold off and get out a minor release for the current master leaving this for later?

Can we ensure that the "old" functionality is tested somewhere in the test battery (I note most, if not all, the tests have had the sections renamed) and what the behaviour is should we mix syntax by accident e.g. script = echo foo with post-command scripting = echo bar.

Should doc/cug-pdf.pdf have been added in here?

**Comment by hjoliver** [comment]
@arjclark - do you mean "major" in the sense of +/- 1k lines, or that it's an important config item?  The number of lines touched is considerably more than I anticipated but they are trivial changes, and it is only a deprecation, and to a closely related item name that should not confuse users.  Also, I did ask for agreement before doing this: https://github.com/cylc/cylc/issues/1384#issue-63131910 (although perhaps @matthewrmshin neglected to inform the "et. al."?... I've only just discovered that I can '@' reference the entire core team at once).  So, given that it is done now I'd rather get it in unless soundly outvoted!  Happy to delay any other purely aesthetic deprecations until cylc-7, however.

(I'll remove the pdf file...)

**Comment by hjoliver** [comment]
> Can we hold off and get out a minor release for the current master leaving this for later?

Yes, I had already pushed this back to "soon" in response to matt's question, but I don't want to punt it all the way to cylc-7 as explained above.

**Comment by arjclark** [comment]
@hjoliver - "major" in that it's an important config item (the number of lines changed is considerable but I appreciate many relate to documentation and test battery tweaks).

I've got no objection to the change in namings being proposed (makes sense to me) but, perhaps, hadn't appreciated the timescale on which it'd be delivered. I'll leave it to @dpmatthews, @benfitzpatrick and @matthewrmshin to express their own opinions.

**Comment by hjoliver** [comment]
> can we ensure that the "old" functionality is tested somewhere in the test battery

I don't think that's necessary so long as the automatic deprecation in parsec works - we just need some tests for that (and in fact matt's current #1396 does a more complex deprecation that isn't working).

> what the behaviour is should we mix syntax by accident e.g. script = echo foo with post-command scripting = echo bar.

That's fine - the auto-deprecation just replaces any instance of the old syntax with new, when the file is parsed.  Consistency is not absolutely necessary for purely syntactic changes.

**Comment by arjclark** [comment]
> I don't think that's necessary so long as the automatic deprecation in parsec works - we just need some tests for that (and in fact matt's current #1396 does a more complex deprecation that isn't working).

Yeah, saw that and did wonder if we needed to be adding in further deprecation tests.

>what the behaviour is should we mix syntax by accident e.g. script = echo foo with post-command scripting = echo bar.
>> That's fine - the auto-deprecation just replaces any instance of the old syntax with new, when the file is parsed. Consistency is not absolutely necessary for purely syntactic changes.

Ok, cool. Can we add a test/tests in that ensure this persists lest one of us breaks it by accident and doesn't notice?

> I've only just discovered that I can '@' reference the entire core team at once

Useful to know about, so if I just write an '@' everyone get's tagged?

Sorry to be the proverbial spanner in the works!

**Comment by benfitzpatrick** [comment]
I'm happy with the change, and have a more aggressive attitude to deprecating and obsoleting
 than most (e.g. strongly supporting pre-cylc-6 syntax removal at cylc 7... another debate).

However, given that we're mid-cylc-major-version, I think a good compromise would be to have a 'silent deprecation' for now - use the auto-renaming parsec deprecation code, but use a keyword
argument to switch off the user notification so they don't see it. We can then officially deprecate it at cylc 7 with a plan to junk it at cylc 8 or something.

**Comment by hjoliver** [comment]
> so if I just write an '@' everyone get's tagged?

@cylc/core 

> hadn't appreciated the timescale on which it'd be delivered

Fair enough - as alluded to above, I was writing a talk last week and it occurred to me that the new syntax looked more sensible and made it easier to fit example suites in large-font slides... so I used it, and quickly made the code changes to match.  A bit rash perhaps!

> Sorry to be the proverbial spanner in the works!

No worries :grin:

**Comment by hjoliver** [comment]
Rebased to remove the stray pdf file.

**Comment by hjoliver** [comment]
>  I'm happy with the change, and have a more aggressive attitude to deprecating and obsoleting
than most (e.g. strongly supporting pre-cylc-6 syntax removal at cylc 7... another debate).

For the record, I will be coming down on the same side of that debate.

**Comment by matthewrmshin** [comment]
What is the behaviour if a suite contains both old and new syntax?

**Comment by hjoliver** [comment]
> What is the behaviour if a suite contains both old and new syntax? (We should prevent mixed syntax like mixing old date-time and ISO8601 date-time in the same suite.)

Ok, my reply above to @arjclark on this wasn't clear.  Individual parsec-deprecated items are upgraded in-place when the file is parsed, so mixed usage is automatically unmixed.  It isn't disallowed because mixing usage is merely untidy, it can't break the suite (but a warning can be printed) - at least that was my thinking when I coded parsec.  Pre/post ISO8601 date-time syntax is not the same kind of simple deprecation of one config item for another, it is much more of a wider-ranging backward compatibility problem.   So ... I could probably be persuaded that we should be stricter on this, but it seems to me that its not strictly necessary.

**Comment by matthewrmshin** [comment]
I think you have left a merge marker under `lib/cylc/broadcast.py` line 31.

```
Traceback (most recent call last):
  File "/home/matt/cylc.git/bin/cylc-run", line 27, in <module>
    from cylc.scheduler import scheduler
  File "/home/matt/cylc.git/lib/cylc/scheduler.py", line 49, in <module>
    from cylc.task_pool import TaskPool
  File "/home/matt/cylc.git/lib/cylc/task_pool.py", line 49, in <module>
    from cylc.broadcast import Broadcast
  File "/home/matt/cylc.git/lib/cylc/broadcast.py", line 31
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax
```

**Comment by hjoliver** [comment]
(sorry, I intended to rerun the test battery to check for merge errors before rejuvinating this pull request... will fix tomorrow!)

**Comment by matthewrmshin** [comment]
Test battery OK with the merge marker removed. I'll look through the change in detail

**Comment by matthewrmshin** [comment]
Broadcast does not appear to be backward compatible. E.g.:

```sh
cylc broadcast --debug -s 'command scripting=true' -p 1 -n foo-1 foo
```

Returns:

```
Traceback (most recent call last):
  File "/home/matt/cylc.git/bin/cylc-broadcast", line 284, in <module>
    validate(setting, SPEC['runtime']['__MANY__'])
  File "/home/matt/cylc.git/lib/parsec/validate.py", line 68, in validate
    raise IllegalItemError( keys, key )
parsec.validate.IllegalItemError: 'Illegal item: command scripting'
```

**Comment by hjoliver** [comment]
(merge marker removed)

I know how to pass broadcast settings through the deprecation process ...

**Comment by matthewrmshin** [comment]
(I must say, this is actually a small change, if we don't have to modify every `suite.rc` in `tests/`!)

**Comment by hjoliver** [comment]
Broadcast settings now get deprecated (just a two line change to do that).

**Comment by hjoliver** [comment]
> (I must say, this is actually a small change, if we don't have to modify every suite.rc in tests/!)

Well I did say it was trivial.  As for all the test suites, I didn't see the point in having every suite test deprecation of the same item, so I just modified them all in-place with ```find``` and ```sed```.

**Comment by hjoliver** [comment]
@arjclark and @matthewrmshin - I've added a new test for all current deprecations and obsoletions.

**Comment by hjoliver** [comment]
Branch updated.

**Comment by matthewrmshin** [comment]
Test battery OK. (The deprecation warning is breaking some tests on Rose's test battery, but should be trivial to fix.)

**Comment by benfitzpatrick** [comment]
I still would like silent deprecation, but if others are happy, fair enough. In that case, (and it's about time too) I'll put up an issue for raising pre-cylc-6 syntax deprecation warnings.

**Comment by dpmatthews** [comment]
I think there is a big difference between introducing a new preferred syntax and deprecating the old one. We should allow a reasonable period before the old syntax is deprecated. Otherwise I think we will annoy users and give them the impression that deprecation warnings are normal and can be ignored.

**Comment by hjoliver** [comment]
Deprecation of of these items is now silent (i.e. the change is made, but no warning is printed).

**Comment by matthewrmshin** [comment]
`tests/deprecations/00-all.t` fails. I think you need to remove line 45 to 49.

**Comment by hjoliver** [comment]
Done (those are the now-silenced deprecation warnings).

**Pull request merged**
