### PR TITLE
gui: fix raw graph for cycling suite, again

### PR DESCRIPTION
**Pull request by matthewrmshin**
Perhaps broken by #2177? (New test fails in current master.) Reported by @arjclark via email.

### CODE REVIEW

**Comment by hjoliver** [comment]
Hmm, yes graph view in the current release fails.  :grimacing:

**Comment by arjclark** [comment]
Unfortunately still not quite working properly. Example suite in the test `02-get-graph-raw-3` works fine (checked). However, updating the suite as follows and the graphing stops working again:
{{{
[cylc]
   [[reference test]]
       required run mode = live
       live mode suite timeout = PT30S
[scheduling]
    initial cycle point = 20200101T0000Z # non purely digit cyclepoint
    final cycle point = 20210101T0000Z
    [[dependencies]]
        [[[P1Y]]]
            graph = t1[-P1Y] => t1
[runtime]
    [[t1]]
        script = """
if [[ "${CYLC_TASK_CYCLE_POINT}" == '20200101T0000Z' ]]; then
    ctb-get-graph-raw \
        'start_point_string=2020' 'stop_point_string=2021' 'group_nodes=T' \
        >"${CYLC_SUITE_RUN_DIR}/ctb-get-graph-raw.out"
fi
"""
}}}

Traceback:
{{{
Traceback (most recent call last):
  File "/net/home/h06/aclark/cylc.git/lib/cylc/network/https/base_client.py", line 206, in _get_data_from_url_with_urllib2
    response = opener.open(req, timeout=self.timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 429, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1068, in http_error_401
    host, req, headers)
  File "/usr/lib64/python2.6/urllib2.py", line 953, in http_error_auth_reqed
    return self.retry_http_digest_auth(req, authreq)
  File "/usr/lib64/python2.6/urllib2.py", line 964, in retry_http_digest_auth
    resp = self.parent.open(req, timeout=req.timeout)
  File "/usr/lib64/python2.6/urllib2.py", line 397, in open
    response = meth(req, response)
  File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.6/urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
Cannot connect: https://eld170.cmpd1.metoffice.gov.uk:43026/info/get_graph_raw?stop_point_string=20210101T0000Z&ungroup_recursive=False&start_point_string=20200101T0000Z&group_nodes=None&ungroup_nodes=None&ungroup_all=False&group_all=True:
}}}

**Comment by matthewrmshin** [comment]
This should now be good.

**Comment by arjclark** [comment]
Cool, now testing as working correctly.

**Pull request merged**
