### PR TITLE
cylc performance: speed up suite elapsed time

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This change speeds up suite and test-battery elapsed times.

It leads to fewer database commits and fewer calls to cylc.version,
both of which can be slow under certain circumstances. For example,
importing cylc.version under a cylc git clone can lead to a 0.5 second
overhead for each call to `cylc jobs-submit` and `cylc task message`.

I can now happily run the test battery with `-j 30`!

@matthewrmshin, please review.

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
N.B. database 1000 lock test occasionally times out under high 'j'.

**Comment by matthewrmshin** [comment]
Docs creation is failing. Try `make clean all`, and you will see the error. It looks like we have a lot of `%` strings in the usage statement, these need to be escaped using `%%`.

**Comment by hjoliver** [comment]
> importing cylc.version under a cylc git clone can lead to a 0.5 second
overhead for each call to cylc jobs-submit and cylc task message

It seems that `git describe` could be very slow under older git versions. On one of our servers, until a recent git upgrade, it could take 10-20 seconds!  I was having to roll a local release tarball at branch head in order to test cylc there.   But, well done for doing this properly :grin:

**Comment by hjoliver** [comment]
@benfitzpatrick - another reason that getting the cylc version from a git clone can be slow, is the scripting for detecting a "dirty" clone, `admin/get-repo-version`:
```
        git update-index -q --refresh 2> /dev/null
        test -z "$(git diff-index --name-only HEAD -- 2> /dev/null)" || VN="$VN-dirty" ;;
```

Can you consider replacing this with:
```
[[  -n "$(git status --untracked-files=no --porcelain)" ]] && VN="$VN-dirty" 
```

(extracted from a discussion here: http://unix.stackexchange.com/questions/155046/determine-if-git-working-directory-is-clean-from-a-script).

**Comment by matthewrmshin** [comment]
I am now happy with the change, and it is definitely much faster.

@hjoliver please review 2. (You are already doing it any way!)

**Comment by hjoliver** [comment]
Good.  All tests pass.

**Pull request merged**
