### PR TITLE
Allow use of custom cycle point format in cylc suite-state calls.

### PR DESCRIPTION
**Pull request by arjclark**
Goes some way to addressing part of #1332 

@hjoliver please review 1
@kaday please review 2

### CODE REVIEW

**Comment by matthewrmshin** [comment]
No automated tests?

**Comment by hjoliver** [comment]
@arjclark - note that today I extended the "automatic polling tasks" to use this new option, on a branch off your branch, and I updated the User Guide for this too.  I'll put this up as a pull request to your branch later (prob. tomorrow...)

**Comment by arjclark** [comment]
> @arjclark - note that today I extended the "automatic polling tasks" to use this new option, on a branch off your branch, and I updated the User Guide for this too. I'll put this up as a pull request to your branch later (prob. tomorrow...)

Cool.

> No automated tests?

I'll see if I can add something. Not sure if I can do anything particularly useful but will have a think.

**Comment by arjclark** [comment]
@hjoliver - have merged in your branch and added automated tests for the template option on both CLI and in suite.

**Comment by hjoliver** [comment]
Review 1: all good.

**Comment by kaday** [comment]
Test-battery failure - cylc-get-config/00-simple.t

**Comment by arjclark** [comment]
@kaday - sorry, working now.

**Comment by kaday** [comment]
Looks okay to me and passes all tests in my environment.

**Pull request merged**
