### PR TITLE
Cleaned up the gcylc stop-suite dialog.

### PR DESCRIPTION
**Pull request by hjoliver**
Removed the obsolete --quick stop option.
Fixed broken stop-after-task option.
Tidied the layout and text.
Some code style corrections.

### CODE REVIEW

**Comment by hjoliver** [comment]
This was motivated by the easy bit of #1282 (gcylc still has broken "stop --quick" option).

The dialog now looks like this:
stop-dialog

**Comment by hjoliver** [comment]
Tested each option manually.

@arjclark - please review.

**Comment by arjclark** [comment]
@hjoliver - looks much nicer to me, confirmed as working on my end with manual testing.

Would it be possible to tweak the wording on the Stop after date-time to make it clear that's the wall clock/actual date time to look at? Could be confused at a glance and not reading all the options with what "Stop after cycle-point" does.

**Comment by hjoliver** [comment]
@arjclark - it's now "Stop after wall-clock date-time".  Note I also altered the "Stop now" text slightly.

**Comment by arjclark** [comment]
Looks good to me.

**Pull request merged**
