### PR TITLE
Improve t-restart-20 robustness

### LINKED ISSUE #2052: new flaky test: ./tests/restart/19-checkpoint.t
Regularly seeing problems with this test getting stuck if not run in isolation.

As far as I can tell the problem lies with the first step of running of the suite not doing what it should prior to restart actions etc.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Rename test as numbering clashes after several merges.

Attempt to fix #2052.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@arjclark please review.

**Comment by arjclark** [comment]
Looks like some sensible changes but test still getting stuck (now ./tests/restart/20-checkpoint.t)

**Comment by matthewrmshin** [comment]
I think I need to see some more evidence of the test getting stuck. I have not seen it for a while now in my environment, and it has been OK on Travis CI as well.

**Comment by arjclark** [comment]
#2052 still sticking from time to time but this is better either way.

**Pull request merged**
