### PR TITLE
gcylc - tree view task progress bars

### PR DESCRIPTION
**Pull request by hjoliver**
Task progress bars based on the mean completion time for each task.

@benfitzpatrick - please review.

gcylc-task-progbars

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
I like this!

**Comment by benfitzpatrick** [comment]
I think the 'succeeded' progress bars should be disappeared (especially as sometimes they finish before the progress bar is full) - otherwise great!

**Comment by hjoliver** [comment]
Branch rebased and squashed.   The progress bars are reset to 0 after the task finishes, which I think is OK (otherwise have to figure out how to dynamically replace cell renderers...)

**Comment by benfitzpatrick** [comment]
Dynamically replacing them would be a pain, I agree!

I wondered if there was a way to have both a CellRendererProgress and a CellRendererText within that column and flip between them - I just had a quick go and it turns out you can:
cell_renderer_switch_screenshot

They don't vertically align in the way that I suspected (no separate sub-column for the cells), so it looks OK, I think.

Example diff:

```diff
diff --git a/lib/cylc/gui/view_tree.py b/lib/cylc/gui/view_tree.py
index 22ab712..275887e 100644
--- a/lib/cylc/gui/view_tree.py
+++ b/lib/cylc/gui/view_tree.py
@@ -115,9 +115,10 @@ Text Treeview suite control interface.
                 tvc.pack_start(crp, False)
                 tvc.set_attributes(crp, pixbuf=11)
             if n == 8:
-                cr = gtk.CellRendererProgress()
-            else:
-                cr = gtk.CellRendererText()
+                prog_cr = gtk.CellRendererProgress()
+                tvc.pack_start(prog_cr, True)
+                tvc.set_cell_data_func(prog_cr, self._set_cell_text_time, n)
+            cr = gtk.CellRendererText()
             tvc.pack_start(cr, True)
             if n == 6 or n == 7 or n == 8:
                 tvc.set_cell_data_func(cr, self._set_cell_text_time, n)
@@ -269,22 +270,24 @@ Text Treeview suite control interface.
                 last_update_date + "T", "", 1)
         if n == 8:
             # Progress bar for estimated completion time.
-            if date_time_string == "":
-                # Family rows.
-                cell.set_property('visible', False)
-            elif date_time_string == "*":
-                # Date-time estimate not available yet.
-                cell.set_property('visible', True)
-                cell.set_property('value', 0)
-            elif not date_time_string.endswith('?'):
-                # Task finished - set back to 0% for aesthetic reasons.
-                cell.set_property('visible', True)
-                cell.set_property('value', 0)
-            else: 
-                # Task running - show progress to estimated finish time.
-                cell.set_property('visible', True)
-                percent = model.get_value(iter_, 12)
-                cell.set_property('value', percent)
+            if isinstance(cell, gtk.CellRendererText):
+                if date_time_string.endswith("?"):
+                    # Task running - show the progress bar instead.
+                    cell.set_property('visible', False)
+                else:
+                    # Task not running - just show text.
+                    cell.set_property('visible', True)
+                    cell.set_property('text', date_time_string)
+            if isinstance(cell, gtk.CellRendererProgress):
+                if date_time_string.endswith("?"):
+                    # Task running - show progress to estimated finish time.
+                    cell.set_property('visible', True)
+                    percent = model.get_value(iter_, 12)
+                    cell.set_property('value', percent)
+                else:
+                    # Task not running - show the text cell instead.
+                    cell.set_property('visible', False)
+                    cell.set_property('value', 0)
         cell.set_property("text", date_time_string)
 
     def get_toolitems( self ):
```

**Comment by hjoliver** [comment]
Nice idea - cut-n-pasted, and tested.

**Comment by hjoliver** [comment]
@benfitzpatrick - I've just had another play with this (with your suggested change), alignment looks fine, if you agree then I think this is good to go.

**Pull request merged**
