### PR TITLE
fix python 2.6 breakage

### PR DESCRIPTION
**Pull request by oliver-sanders**
Broken by: https://github.com/cylc/cylc/commit/63b98cf267e6c34918a2f39a194fb8edc95ee8d7

### CODE REVIEW

**Comment by sadielbartholomew** [comment]
Oops!

I'm just running the full test battery to check things are fully in order after this (i.e. that nothing else is causing breakages for v2.6) but from the interactive shell, this change makes sense:

```
Python 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> a="hello"
>>> print "({})".format(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: zero length field name in format
>>> print "({0})".format(a)
(hello)
```
Well diagnosed.

**Comment by hjoliver** [comment]
Good spotting @oliver-sanders 

(Note @kinow and I don't have access to Python 2.6 on our work platforms anymore ... I suppose we might be able to do it in a VM or container on our laptops ... but I see Python 2.6 was released in Oct 2008; looking forward saying good riddance to it.)

**Comment by matthewrmshin** [comment]
Unfortunately we have a platform on Python 2.6.9 (October 2013) that we still have to support.

**Comment by hjoliver** [comment]
@matthewrmshin - OK, I think we will just rely on the UK team for testing on Python 2.6 then.

**Comment by kinow** [comment]
_\*Bruno approves and hides\*_

Sorry for breaking it for Python 2.6 yet again @oliver-sanders! Looking at [Anaconda archives](https://repo.continuum.io/archive/), I think I can try to install 2.6 and ask PyCharm to support compatibility for that version.

Most of my changes follow a work-flow like 

- _"Oh, that code is 3.7+, need to fix it"_
- _"Hmmm, still 3.0+..."_
- _"Now it's 2.7, but needs future/extra modules"_
- _"A-ha! 2.7! Perfect! Submit pull request!!!"_
- _"And I just broke 2.6 again"_

But hopefully instructing my IDE to double-check it's OK for 2.6 for now will reduce the number of fixes like this one.

Thanks, LGTM
Bruno

**Comment by oliver-sanders** [comment]
Hopefully we will be able to move away from this arcane dependency in the near future, for the moment...

**Pull request merged**
