### PR TITLE
Random ssl cert serial numbers.

### PR DESCRIPTION
**Pull request by hjoliver**
Browsers don't like multiple certificates with the same number and issuer.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
I guess we should be good enough with a big random number - even though it may still get in trouble? Should we head towards single certificate per user per host to avoid this issue?

**Comment by hjoliver** [comment]
The random number is sufficient huge that the odds of clash are effectively zero.  A single certificate per user per host is probably a good idea, but maybe we should wait to see how upcoming web GUI and authentication plans pan out?

**Comment by matthewrmshin** [comment]
OK. Agreed.

**Comment by hjoliver** [comment]
I've taken your alternative method - it's much cleaner (although needs to be int not hex).

**Comment by matthewrmshin** [comment]
@oliver-sanders please sanity check.

**Comment by hjoliver** [comment]
Isn't it 2^159?

**Comment by hjoliver** [comment]
i.e. 2^(20*8)

**Comment by oliver-sanders** [comment]
Whoops, Bytes not bits! That gives us 48 digits rather than 6.

**Pull request merged**
