### PR TITLE
Validation: fail cyclic dependencies.

### LINKED ISSUE #515: Full cyclic dependency analysis
From @matthewrmshin: https://github.com/cylc/cylc/pull/513#issuecomment-19095431

Graphviz apparently has a utility called "acyclic" that does this, which pygraphviz appears to cover.  

This might be useful too: http://blog.jasonantman.com/2012/03/python-script-to-find-dependency-cycles-in-graphviz-dot-files/

### PR DESCRIPTION
**Pull request by hjoliver**
Close #515.

This detects cyclic dependence and reports the "back edges" found.
```
   graph = a => b => c => d => a => z

$ cylc val foo
Back-edges:
  d.1 => a.1
'ERROR: cyclic dependence detected (graph the suite to see back-edges).'
```

Validation fails the suite but you can still graph it (or run it), to see the back-edges:

back-edge

The special case of self-edges was already handled, but not quite correctly - it didn't work with special triggers like "f:fail => f".  Self-edges can be generated by accidentally making a family depend on one of its members or vice versa.  They are not detected by the full cyclic check because they get eliminated (by (py)graphviz?) from the graph, but still generate prerequisites that stall the suite. [UPDATE: this was due to my use of "strict" graphs in pygraphviz; now fixed (below)]

```
   graph = FAM:succeed-all => f  & g => z   # where f, g, h are members of FAM

$ cylc val foo
Self-edges found in "FAM:succeed-all => f & g => z":
  f => f
  g => g
'ERROR: cyclic dependence detected (graph the suite to see back-edges)'
```

### CODE REVIEW

**Comment by hjoliver** [comment]
@matthewrmshin - please review (or reassign).

**Comment by matthewrmshin** [comment]
```cfg
[scheduling]
    initial cycle point = 20200202
    final cycle point = 20300303
    [[dependencies]]
        [[[P1D]]]
            graph = """
t1[-P1D] => t1
"""
```

On `cylc validate`, I get:

```
Self-edges found in "t1[-P1D] => t1":
  t1 => t1
'ERROR: self-edges detected'
```

**Comment by hjoliver** [comment]
Ah, crap, that's definitely a spanner in the works :grimacing:

**Comment by hjoliver** [comment]
That's got it, I think.  I've allowed the abstract graph to hold self-edges, then detect and fail them later (as for the cyclic dependency check) when the graph node names contain concrete cycle times.

 This has the nice side-effect of making immediate suicide (which is usually not a good idea)  visible like this:
self-suicide

and redundant dependencies (which aren't really a problem, but they're untidy) like this:

redundant-deps

**Comment by matthewrmshin** [comment]
It looks like the latest change has broken the new test `tests/validate/35-fail-self-edges.t`.

**Comment by matthewrmshin** [comment]
For some reason, I cannot get `tests/cyclers/30-9999_rollover.t` to pass either.

**Comment by hjoliver** [comment]
> For some reason, I cannot get tests/cyclers/30-9999_rollover.t to pass either.

Fixed. The reason for this was the new cyclic dependence detection creates graph nodes with concrete cycle points during validation, so the expected failure due to date rollover in this test occurred during validation rather than at run time.  I've adjusted the test to make it pass validation again, by limiting the number of cycle points generated for the graph.

**Comment by hjoliver** [comment]
Test battery passes in my environment.

**Pull request merged**
