### PR TITLE
Fix job kill hold-retry logic

### PR DESCRIPTION
**Pull request by matthewrmshin**
Prevent kill+term logic from releasing a task from the *held (retrying)* status.

The sequence of events looks like this:
1. A task job started.
2. User invokes `cylc kill ...`.
3. Suite invokes `cylc jobs-kill ...` and set task state to `running (held)`.
4. `cylc jobs-kill ...` returns. Callback handles this as a `failed` message with a retry lined up, and set task state to `held (retrying)`.
5. Job terminated by batch system e.g. PBS, and send back a `failed/TERM` message. This is processed as above.
   * Previously, it will set the task state to `retrying`, forgetting the `held` status.
   * Now, it will respect the `held (retrying)` status as equivalent to the `retrying` status for this occasion.

Also change log entry format to improve understanding of what goes on behind the scene. The change looks a bit like this:

```diff
- [foo.1] -(current:submitted)> started at 2017-03-30T09:46:10Z
+ [foo.1] status=submitted: (received)started at 2017-03-30T09:46:10Z for job(01)
```

Rationale:
* Previous format is easy to be mistaken for a change of task state from *submitted* to *started*.
  * (After receiving the message, the new task state is *running* (not *started*).)
* New format is clear that it is a message received.
* New format includes the submit number.
* New format marks internal and polled messages the same way.

Address #3052 for 7.8.x.

Will forward port to master.

### CODE REVIEW

**Comment by kinow** [comment]
Running a PBS job, with a single task that sleeps for 2 minutes. While it's sleeping in PBS, I tried `cylc kill`, but got some weird error (using latest `7.8.x`).

```
testuser@cylc:~$ cylc run pbs1
            ._.                                                       
            | |           The Cylc Suite Engine [7.8.1-139-gbe1477]   
._____._. ._| |_____.           Copyright (C) 2008-2019 NIWA          
| .___| | | | | .___|   & British Crown (Met Office) & Contributors.  
| !___| !_! | | !___.  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
!_____!___. |_!_____!  This program comes with ABSOLUTELY NO WARRANTY;
      .___! |          see `cylc warranty`.  It is free software, you 
      !_____!           are welcome to redistribute it under certain  

*** listening on https://cylc:43073/ ***

To view suite server program contact information:
 $ cylc get-suite-contact pbs1

Other ways to see if the suite is still running:
 $ cylc scan -n 'pbs1' cylc
 $ cylc ping -v --host=cylc pbs1
 $ ps -opid,args 2076  # on cylc

testuser@cylc:~$ cylc kill pbs1
Traceback (most recent call last):
  File "/opt/cylc/lib/cherrypy/_cprequest.py", line 679, in respond
    response.body = self.handler()
  File "/opt/cylc/lib/cherrypy/lib/encoding.py", line 230, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/cylc/lib/cherrypy/lib/jsontools.py", line 63, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/opt/cylc/lib/cherrypy/_cpdispatch.py", line 66, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: items')
Bad return code: https://cylc:43073/kill_tasks?: 404 Client Error: Not Found for url: https://cylc:43073/kill_tasks
testuser@cylc:~$ cylc scan
pbs1 testuser@cylc:43073
```

**Comment by kinow** [comment]
I can confirm the old log formats were

```
2019-04-09T01:10:29Z INFO - [a.1] -(current:ready) submitted at 2019-04-09T02:10:29+01:00
2019-04-09T01:10:29Z INFO - [a.1] -health check settings: submission timeout=None
2019-04-09T01:10:30Z INFO - [a.1] -(current:submitted)> started at 2019-04-09T02:10:29+01:00
```

And the new format displayed for me is now

```
2019-04-09T01:23:00Z INFO - [a.1] status=ready: (internal)submitted at 2019-04-09T02:23:00+01:00 for job(01)
2019-04-09T01:23:00Z INFO - [a.1] -health check settings: submission timeout=None
2019-04-09T01:23:01Z INFO - [a.1] status=submitted: (received)started at 2019-04-09T02:23:00+01:00 for job(01)
```

But I can't see the `held` status. For both this branch and `7.8.x` I have the same output:

```
2019-04-09T01:15:12Z INFO - [client-command] poll_tasks testuser@cylc:cylc-poll 0e4eb0d7-e28f-4838-95e5-eb8087c96c6f
2019-04-09T01:15:13Z INFO - Command succeeded: poll_tasks([u'a'], poll_succ=False)
2019-04-09T01:15:13Z INFO - Processing 1 queued command(s)
	+	poll_tasks([u'a'], poll_succ=False)
2019-04-09T01:15:13Z INFO - [b.1] -(current:running)> succeeded at 2019-04-09T01:15:12Z
2019-04-09T01:15:14Z INFO - [a.1] -(current:running)(polled) started at 2019-04-09T02:15:09+01:00
2019-04-09T01:15:32Z INFO - [client-command] kill_tasks testuser@cylc:cylc-kill 27ba55bd-a350-4ef7-875d-2dd7e2c41658
2019-04-09T01:15:33Z INFO - Command succeeded: kill_tasks([u'a.*'])
2019-04-09T01:15:33Z INFO - Processing 1 queued command(s)
	+	kill_tasks([u'a.*'])
2019-04-09T01:15:34Z INFO - [a.1] -(current:running) failed at 2019-04-09T01:15:34Z
2019-04-09T01:15:34Z CRITICAL - [a.1] -job(01) failed
2019-04-09T01:15:34Z INFO - [a.1] -job(01) killed
2019-04-09T01:15:34Z CRITICAL - [a.1] -(current:failed)> failed/TERM at 2019-04-09T02:15:33+01:00
2019-04-09T01:15:34Z CRITICAL - [a.1] -job(01) failed
2019-04-09T01:15:35Z WARNING - suite stalled`
```

and DB

```
sqlite> select * from task_events;
a|1|2019-04-09T01:15:09Z|1|submitted|
a|1|2019-04-09T01:15:10Z|1|started|
b|1|2019-04-09T01:15:12Z|1|submitted|
b|1|2019-04-09T01:15:12Z|1|started|
b|1|2019-04-09T01:15:13Z|1|succeeded|
a|1|2019-04-09T01:15:34Z|1|failed|
a|1|2019-04-09T01:15:34Z|1|signaled|TERM
a|1|2019-04-09T01:15:34Z|1|critical|failed/TERM
```

So I suspect it would require a few more steps to reproduce this case. But I can at least confirm it works the same before/after the change here, so nothing appears to be broken by this change :grin: and code looks good, so keeping +1

Now off to try some JupyterHub on these PBS containers.

**Comment by matthewrmshin** [comment]
You should be able to see the `held` state if you use `SELECT * FROM task_pool` or `SELECT * FROM task_states`.

Otherwise, starting you suite in debug mode should also do the trick because the state change logging is done at the end of `cylc.task_state.TaskState._set_state` with a `LOG.debug`. (Should we change this to `LOG.info`?)

**Comment by matthewrmshin** [comment]
(Removed change due to #3094, now addressed by #3100.)

**Comment by kinow** [comment]
Testing again, and now noticed the `held` state in the logs.

```
testuser@cylc:~$ cylc cat-log pbs1
2019-04-12T01:51:37Z INFO - Suite server: url=https://cylc:43051/ pid=270
2019-04-12T01:51:37Z INFO - Run: (re)start=0 log=1
2019-04-12T01:51:37Z INFO - Cylc version: 7.8.1-147-g981bd
2019-04-12T01:51:37Z INFO - Run mode: live
2019-04-12T01:51:37Z INFO - Initial point: 1
2019-04-12T01:51:37Z INFO - Final point: 1
2019-04-12T01:51:37Z INFO - Cold Start 1
2019-04-12T01:51:38Z INFO - [a.1] -submit-num=01, owner@host=pbs
2019-04-12T01:51:40Z INFO - [a.1] status=ready: (internal)submitted at 2019-04-12T02:51:39+01:00 for job(01)
2019-04-12T01:51:40Z INFO - [a.1] -health check settings: submission timeout=None
2019-04-12T01:51:41Z INFO - [a.1] status=submitted: (received)started at 2019-04-12T02:51:39+01:00 for job(01)
2019-04-12T01:51:41Z INFO - [a.1] -health check settings: execution timeout=None
2019-04-12T01:51:42Z INFO - [b.1] -submit-num=01, owner@host=cylc
2019-04-12T01:51:43Z INFO - [b.1] status=ready: (internal)submitted at 2019-04-12T01:51:42Z for job(01)
2019-04-12T01:51:43Z INFO - [b.1] -health check settings: submission timeout=None
2019-04-12T01:51:43Z INFO - [client-command] poll_tasks testuser@cylc:cylc-poll 48178bbb-8e59-4f35-ae71-ee525f8dd965
2019-04-12T01:51:44Z INFO - Command succeeded: poll_tasks([u'a'], poll_succ=False)
2019-04-12T01:51:44Z INFO - Processing 1 queued command(s)
	+	poll_tasks([u'a'], poll_succ=False)
2019-04-12T01:51:44Z INFO - [b.1] status=submitted: (received)started at 2019-04-12T01:51:42Z for job(01)
2019-04-12T01:51:44Z INFO - [b.1] -health check settings: execution timeout=None
2019-04-12T01:51:44Z INFO - [b.1] status=running: (received)succeeded at 2019-04-12T01:51:43Z for job(01)
2019-04-12T01:51:45Z INFO - [a.1] status=running: (polled)started at 2019-04-12T02:51:39+01:00 for job(01)
2019-04-12T01:51:53Z INFO - [client-command] kill_tasks testuser@cylc:cylc-kill df861606-64d0-498b-b1bf-ea9dbe00e728
2019-04-12T01:51:54Z INFO - Command succeeded: kill_tasks([u'a.*'])
2019-04-12T01:51:54Z INFO - Processing 1 queued command(s)
	+	kill_tasks([u'a.*'])
2019-04-12T01:51:55Z INFO - [a.1] status=running (held): (internal)failed at 2019-04-12T01:51:55Z for job(01)
2019-04-12T01:51:55Z CRITICAL - [a.1] -job(01) failed
2019-04-12T01:51:55Z INFO - [a.1] -job(01) killed
2019-04-12T01:51:55Z CRITICAL - [a.1] status=failed: (received)failed/TERM at 2019-04-12T02:51:54+01:00 for job(01)
2019-04-12T01:51:55Z CRITICAL - [a.1] -job(01) failed
2019-04-12T01:51:56Z WARNING - suite stalled
```

From

```
testuser@cylc:/opt/cylc$ git log -n 1
commit 981bd6638e2a0e74b56bea2b090ff0ffaf4b655c
Author: Matt Shin <matthew.shin@metoffice.gov.uk>
Date:   Fri Mar 29 16:41:44 2019 +0000

    Fix job kill hold-retry logic
    
    Prevent kill+term logic from unholding a retry (hold) status.
testuser@cylc:/opt/cylc$
```

But from `7.8.x`, the `held` state is not shown in the logs.

```
testuser@cylc:~$ cylc cat-log pbs1
2019-04-12T01:56:24Z INFO - Suite server: url=https://cylc:43053/ pid=80
2019-04-12T01:56:24Z INFO - Run: (re)start=0 log=1
2019-04-12T01:56:24Z INFO - Cylc version: 7.8.1-158-gb02ba
2019-04-12T01:56:24Z INFO - Run mode: live
2019-04-12T01:56:24Z INFO - Initial point: 1
2019-04-12T01:56:24Z INFO - Final point: 1
2019-04-12T01:56:24Z INFO - Cold Start 1
2019-04-12T01:56:25Z INFO - [a.1] -submit-num=1, owner@host=pbs
2019-04-12T01:56:26Z INFO - [a.1] -(current:ready) submitted at 2019-04-12T02:56:26+01:00
2019-04-12T01:56:26Z INFO - [a.1] -health check settings: submission timeout=None
2019-04-12T01:56:27Z INFO - [a.1] -(current:submitted)> started at 2019-04-12T02:56:27+01:00
2019-04-12T01:56:27Z INFO - [a.1] -health check settings: execution timeout=None
2019-04-12T01:56:28Z INFO - [b.1] -submit-num=1, owner@host=cylc
2019-04-12T01:56:29Z INFO - [client-command] poll_tasks testuser@cylc:cylc-poll 83c4d741-b3c0-42ff-a2f9-0992c96b7b9b
2019-04-12T01:56:29Z INFO - Command succeeded: poll_tasks([u'a'], poll_succ=False)
2019-04-12T01:56:29Z INFO - Processing 1 queued command(s)
	+	poll_tasks([u'a'], poll_succ=False)
2019-04-12T01:56:29Z INFO - [b.1] -(current:ready) submitted at 2019-04-12T01:56:29Z
2019-04-12T01:56:29Z INFO - [b.1] -health check settings: submission timeout=None
2019-04-12T01:56:29Z INFO - [b.1] -(current:submitted)> started at 2019-04-12T01:56:29Z
2019-04-12T01:56:29Z INFO - [b.1] -health check settings: execution timeout=None
2019-04-12T01:56:30Z INFO - [a.1] -(current:running)(polled) started at 2019-04-12T02:56:27+01:00
2019-04-12T01:56:30Z INFO - [b.1] -(current:running)> succeeded at 2019-04-12T01:56:29Z
2019-04-12T01:56:31Z INFO - [client-command] kill_tasks testuser@cylc:cylc-kill aa9615e9-8a5b-4267-9b54-f5bf2e46b8b8
2019-04-12T01:56:31Z INFO - Command succeeded: kill_tasks([u'a.*'])
2019-04-12T01:56:31Z INFO - Processing 1 queued command(s)
	+	kill_tasks([u'a.*'])
2019-04-12T01:56:31Z INFO - [a.1] -(current:running) failed at 2019-04-12T01:56:31Z
2019-04-12T01:56:31Z CRITICAL - [a.1] -job(01) failed
2019-04-12T01:56:31Z INFO - [a.1] -job(01) killed
2019-04-12T01:56:32Z CRITICAL - [a.1] -(current:failed)> failed/TERM at 2019-04-12T02:56:31+01:00
2019-04-12T01:56:32Z CRITICAL - [a.1] -job(01) failed
2019-04-12T01:56:32Z WARNING - suite stalled
```

So looks like it correctly passed by the `held` state if I understood it correctly? :tada:

**Comment by hjoliver** [comment]
(I'll merge this; #3052 will remain open till the forward-port PR is done).

**Pull request merged**
