### PR TITLE
gcylc: count down to next reconnect attempt

### PR DESCRIPTION
**Pull request by matthewrmshin**
Rename `Reset Connection Polling` to `Reset Connection Schedule` to avoid terminology confusion (with polling of task jobs).
Add tool button for `Reset Connection Schedule`.
Set sensitivity of `Reset Connection Schedule` to True only when suite is stopped.
Reconnection count down in ISO8601 duration next to last update time.

Partially address #1576. @hjoliver @benfitzpatrick please review.

### CODE REVIEW

**Comment by hjoliver** [comment]
Very nice, I like the countdown timer.  A few thoughts on possible tweaks:

 * Is "Reset Connection Schedule" too much information for users?   It could be just "(Re)connect Now", and the timer will make it clear that there is a delay before subsequent attempts
 * Should the timer briefly report "Not connected" or "Suite not running?" at the first failure to connect?
 * If the button is pressed - i.e. a manual reconnect attempt - should a dialog box pop up to report failure to connect?

**Comment by matthewrmshin** [comment]
@hjoliver Bullet points 1, 2, 4 addressed. I had a brief attempt at bullet point 3, but the popup dialog box annoyed me during testing, so I thought it best to give it a miss.

**Comment by benfitzpatrick** [comment]
View menu view-adjustment options should reset the connection polling. Update time can flip between last updated time and next-reconnection-time.

**Comment by matthewrmshin** [comment]
View changes now reset connection. Update time flip now fixed.

**Comment by hjoliver** [comment]
Review 1 - good, tested, over to @benfitzpatrick.

**Pull request merged**
