### PR TITLE
Fix constant state dumps for queued tasks

### LINKED ISSUE #1744: high CPU use due to continual state dumping
(from @MartinDix)

We occasionally see cylc server processes with high CPU usage for long periods.  The cause of this seems to be that they are continually writing files to cylc-run/SUITE/state, e.g. in this case at a frequency of about 1.5 s (username removed to protect the innocent)

```
% ls -l ..../state
1798144 Mar  1 14:32 cylc-suite.db
     29 Mar  1 14:32 state -> state.20160301T033226.531301Z
  69956 Mar  1 14:32 state.20160301T033212.313480Z
  69956 Mar  1 14:32 state.20160301T033213.906387Z
  69956 Mar  1 14:32 state.20160301T033215.450920Z
  69956 Mar  1 14:32 state.20160301T033217.007761Z
  69956 Mar  1 14:32 state.20160301T033218.547831Z
  69956 Mar  1 14:32 state.20160301T033220.227907Z
  69956 Mar  1 14:32 state.20160301T033221.708751Z
  69956 Mar  1 14:32 state.20160301T033223.677265Z
  69956 Mar  1 14:32 state.20160301T033225.011035Z
  69956 Mar  1 14:32 state.20160301T033226.531301Z
```

These files are all identical apart from the internal timestamp. In suites behaving normally it seems  these files are only written when something changes (e.g. a task finishes). Here however nothing seems to be changing at this high frequency. The log files and cylc-suite.db aren't being modified at this frequency.

I've only seen this behaviour in complex NWP suites with lots of tasks (e.g. state file has ~1000 lines). The high CPU usage can also come and go while the suite runs.

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This fixes #1744 where the state file is continually dumped
if the task pool contains a queued task.

This is due to the ready_to_run check in process_tasks in scheduler.py
returning True if any task is queued and has reached its start time.

The fix is to only update the state summary if we really think
something has changed. This is a good thing to be doing anyway.

@hjoliver, @matthewrmshin please review.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@benfitzpatrick as discussed, any chance of a new test?

**Comment by benfitzpatrick** [comment]
I've added a very simple test based on another in the `tests/state-dump` directory - it just counts the state files. It is not as cool as you wished!

**Comment by matthewrmshin** [comment]
Change looks OK. Tests OK in my environment with and without global configuration.

**Comment by hjoliver** [comment]
Thanks - you guys are machines :grinning: :

**Comment by hjoliver** [comment]
All good, tests passing here.

**Pull request merged**
