### PR TITLE
cylc show: multi-task interface

### LINKED ISSUE #2045: "view prerequisites" fails for tasks in the runahead pool
(the method is presumably assuming all tasks are in the main pool - easy to fix).

foo

### PR DESCRIPTION
**Pull request by matthewrmshin**
- cylc show: can now show multiple task name and/or task ID.
- cylc gui: fix view prerequisites for runahead tasks.

Fix #2045. @hjoliver @arjclark please review.

### CODE REVIEW

**Comment by arjclark** [comment]
@matthewrmshin - can you add/update a test for the cylc show multi-id/task functionality.

**Comment by arjclark** [comment]
Review 2 Looks OK to me. No problems from the test-battery in my environment.

**Comment by hjoliver** [comment]
@matthewrmshin - this doesn't seem to have the desired effect.   E.g. `cylc show foo */baz` returns nothing in a test suite `foo` with a task `baz` instance in several cycle points (the same args do work e.g. for `cylc remove` .  Which suggests the new functionality needs a test too...

**Comment by matthewrmshin** [comment]
HI @hjoliver I am on leave today and tomorrow (Tuesday and Wednesday). I'll take a look at this again when I am back at work on Thursday.

**Comment by matthewrmshin** [comment]
Logic for the `CYCLE/TASK` syntax should now be fixed. New test added. Branch re-based and squashed.

**Pull request merged**
