### PR TITLE
global.cfg: per-host retrieve job logs settings and task events settings

### LINKED ISSUE #1529: siterc: allow setting of [runtime][TASK][event hooks] and [events]
Follow on from #1503. Apply #1501 ability to set defaults for hooks at task runtime event hooks/events options.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Add ability to configure retrieve job logs settings and task events settings in `global.cfg`.

Close #1529.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@hjoliver @arjclark please review.

**Comment by hjoliver** [comment]
Review 1: Looks good, tests as working.

**Comment by matthewrmshin** [comment]
Due to the large number of recent changes to master, I have re-based the branch against it. There was no conflict, and the test battery continue to behave the same.

**Comment by arjclark** [comment]
I haven't forgotten about this - am currently trying to get the test battery to pass...

**Comment by arjclark** [comment]
Now passing in my environment.

**Pull request merged**
