### PR TITLE
Anatomy of a job script (Cylc-8)

### PR DESCRIPTION
**Pull request by hjoliver**
Cylc-8 companion of #3107

### CODE REVIEW

**Comment by hjoliver** [comment]
One approval plus 👍 from Matt on the 7.8.x version of this will do, for this small doc-only change.

**Comment by hjoliver** [comment]
Travis fail unrelated.

**Comment by hjoliver** [comment]
(@kinow approved, but removing the review request for Sadie seems to have reset the approval icon).

**Comment by matthewrmshin** [comment]
:+1:

**Pull request merged**
