### PR TITLE
Remove get_unix_time_from_time_string bottleneck and fix non-Gregorian logging times

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This supercedes #1974.

`get_unix_time_from_time_string` had become a major performance bottleneck due to
initialisation of the `TimePointParser` on every function call.

This change reduces the amount of calls to the function, uses a pre-initialised parser, and
uses `datetime` where possible. The use of `datetime` also fixes the non-Gregorian calendar issues reported in #1974. It's now very fast when the time_string input is in UTC, and still less than half a millisecond per call for non-UTC time strings.

@matthewrmshin, @hjoliver please review.

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
A quick hack (unit-testy) of this new code for a 31 August time string returns a unix time without falling over, but returns a unix time that matches the same time on 1 September... more work to do tomorrow to fix that.

**Comment by benfitzpatrick** [comment]
Ok, am now happier. I've used `datetime.strptime` to parse the datetime strings, with `isodatetime` relegated to time zone parsing.

**Comment by matthewrmshin** [comment]
Looks OK. Tests OK in my environment. As discussed, please add a test to ensure we don't hit the problem of parsing a date string with the 31st day of a month when under the 360day calendar.

**Comment by hjoliver** [comment]
Looks fine to me.

**Comment by benfitzpatrick** [comment]
Bunged in a 360-calendar test which fails on master. It actually fails officially due to a string - int mismatch in the test - the old code returned a string...

**Pull request merged**
