### PR TITLE
Deliberately remove all but validate tests...

### PR DESCRIPTION
**Pull request by arjclark**
Not for merge

### CODE REVIEW

**Comment by hjoliver** [comment]
@arjclark - you can just change line 70 in .travis.yml to select the test(s) you want.

**Comment by hjoliver** [comment]
(of course you may have some other nefarious purpose here :grin: ...)

**Comment by arjclark** [comment]
@hjoliver - yeah, your way would've been the right way to do it had I remembered where to find the travis config file...

**Comment by hjoliver** [comment]
@arjclark - do we have a problem that warrants postponing the release a bit longer? (I was just going to do it)

**Comment by arjclark** [comment]
@matthewrmshin and I have noticed the travis build is failing on master and trying to work out why. I'll leave to him to say if he thinks it needs postponing or not (can't reproduce the problem on our machines so probably not really an issue...)

**Comment by hjoliver** [comment]
When I was setting up TCI initially, it started failing badly for large numbers of tests on hjoliver/cylc, for the exact same branches that worked fine on cylc/cylc , fixed by turning off TCI on my own fork (i.e. not fixed).

**Comment by arjclark** [comment]
It's definitely a consideration :grin: Just hacking around to try and identify what the problem is...

**Comment by matthewrmshin** [comment]
I am testing Travis CI in my own fork. I am getting this for some reason:

```
$ git describe --abbrev=4 --tags HEAD

fatal: No names found, cannot describe anything.
```

**Comment by arjclark** [comment]
@matthewrmshin - likewise.

**Comment by arjclark** [comment]
Looks like git might be broken on TCI

**Comment by matthewrmshin** [comment]
Looks like something in Travis CI has changed? Using my own fork, using a branch of master, master~1 and master~2, I am getting identical broken behaviour.

I am reasonably confident that it is not our latest change that is broken.

@hjoliver please go ahead with the release.

**Comment by arjclark** [comment]
Agreed here.

**Comment by hjoliver** [comment]
Yep.  I restarted a build that had previously passed, and it failed.  So something has broken on TCI.

**Pull request closed without merging**
