### PR TITLE
Subprocpool: use SpooledTemporaryFile instead of TemporaryFile

### LINKED ISSUE #2999: Fail to create temporary file if TMPDIR does not exist
A related problem to #2976.

Some HPC environment sets up a unique `TMPDIR` for users when they login. This normally gets cleaned up on logout.

When the workflow server (i.e. suite server program) starts up and daemonizes, however, the double fork may trigger a premature clean up process of `TMPDIR` ( - suspected without much evidence). This means that `TMPDIR` is still defined, but points to a non-existent location. This causes any subsequent attempts to call `mkstemp` (and related, e.g. Python's `tempfile.TemporaryFile`) to fail.

Possible solutions:
* Always call `if os.getenv('TMPDIR'): os.makedirs(os.getenv('TMPDIR'), exist_ok=True)` before creating a temporary file.
* On workflow server (i.e. suite) start up, ignore environment's `TMPDIR` and set up a temporary directory under the suite run directory and point `TMPDIR` to it.

@cylc/core Any preference or other suggestions?

### PR DESCRIPTION
**Pull request by matthewrmshin**
Use SpooledTemporaryFile to avoid using the file system - should in theory eliminate the reliance on TMPDIR.

Note: The biggest usage of this is remote job submission - with up to 100 job files being sent via STDIN to the remote host per command. A job file is typically about 1-2K in size, so even 100 of them should only be ~200K. In the default configuration where we have a pool of 4 sub-processes, this should still be less than 1M. Unlikely to be a big issue for a modern computing host?

Fix #2999.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
I finally have a good understanding of the problem. To repeat the bug:

1. Create a temporary directory.
2. Export `TMPDIR` to point to the temporary directory. Start Python.
3. Import `tempfile`.
4. Call `tempfile.gettempdir()` while temporary directory still exists.
5. Delete temporary directory.
6. Now calling `TemporaryFile()` will result in a traceback.
7. But `SpooledTemporaryFile()` is fine!

```
$ mkdir tmp
$ TMPDIR=$PWD/tmp python3
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> import os
>>> tempfile.gettempdir()
'/home/matt/cylc.git/tmp'
>>> os.rmdir('tmp')
>>> tempfile.gettempdir()
'/home/matt/cylc.git/tmp'
>>> tempfile.TemporaryFile()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matt/miniconda3/lib/python3.7/tempfile.py", line 618, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/matt/miniconda3/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
FileNotFoundError: [Errno 2] No such file or directory: '/home/matt/cylc.git/tmp/tmpmrxd01mn'
>>> tempfile.SpooledTemporaryFile()
<tempfile.SpooledTemporaryFile object at 0x7fbf2fe60358>
>>> 
```

**Comment by matthewrmshin** [comment]
(Lesson learnt: Should have thought about this easy solution before!)

**Comment by hjoliver** [comment]
> I finally have a good understanding of the problem. To repeat the bug:..

But do you understand how that scenario is occurring in our code?

**Comment by hjoliver** [comment]
Also, Python docs say SpooledTemporyFiles are written to disk if they exceed a certain size etc.; which will presumably cause the same error if the directory is gone ... can that be a problem for us?

https://docs.python.org/2/library/tempfile.html#tempfile.SpooledTemporaryFile

**Comment by matthewrmshin** [comment]
The scenario is quite clear. Suite starts with temporary directory. Double forked. Load tempfile module. Use once. Temporary directory is removed by external clean up. Now tempfile module points to the wrong temporary directory.

**Comment by matthewrmshin** [comment]
Not specifying `max_size` here so should be okay.

**Comment by matthewrmshin** [comment]
Similar problem has occurred with the `qsub` command at our site and at another site with similar temporary directory clean up functionality.

**Comment by kinow** [comment]
Today-I-Learned about `SpooledTemporaryFile`. So much to learn in Python 😨 ! Reading the docs and bugs now. Looks like there is only one serious bug with version field set to 3.5 and 3.6: [ SpooledTemporaryFile doesn't correctly preserve data for text (non-binary) SpooledTemporaryFile objects when Unicode characters are written ](https://bugs.python.org/issue26730).

So I think we just have to be careful if using Unicode characters with `SpooledTemporaryFile` until the bug is fixed?

**Comment by hjoliver** [comment]
OK, so external temp dir clean up is to blame, that makes sense.  At once point we were considering garbage collection due to not keeping a reference to the file in the main process (although it seemed that was not the case).

**Comment by matthewrmshin** [comment]
We should be OK with Unicode, as we only use `SpooledTemporaryFile` in binary mode. To prove that, I have now added a `stdin_str` test with a Unicode character.

**Pull request merged**
