### PR TITLE
cylc gsummary: retrieval time not suite updated

### LINKED ISSUE #1434: cylc gsummary: tooltip for updated showing suite update time not retrieval time
In gsummary with the updated column showing, the tooltip reports that the info was retrieved at the time of the last suite update. This should be corrected to the time at which gsummary retrieved this information.

### PR DESCRIPTION
**Pull request by kaday**
Closes #1434

### CODE REVIEW

**Comment by kaday** [comment]
@arjclark please review

**Comment by kaday** [comment]
@arjclark I had a better idea in my sleep, implemented it and rebased, that is why the order may seem squiffy.

**Comment by arjclark** [comment]
For a running suite, on expanding to cycle view, I get this error chucked out when I use mouseover for a tooltip on the status column:

```
Traceback (most recent call last):
  File ".../cylc.git/lib/cylc/gui/gsummary.py", line 575, in _on_query_tooltip
    status, number = status_number.rsplit(" ", 1)
ValueError: need more than 1 value to unpack
```

Can't reproduce on master.

**Comment by kaday** [comment]
Fixed and tested, it now works. @arjclark please review

**Comment by arjclark** [comment]
Looks good to me. Manually tested as working in my environment. No problems returned from the test battery.

**Pull request merged**
