### PR TITLE
gscan: visual notification of new errors

### LINKED ISSUE #1887: gscan: task failures: visual notification of new errors
Follow-on from work in #1884 - have some kind of notification for 'new' failures in suites.

For example, we could have a warning triangle icon next to the state boxes that appears when tasks fail and disappears on click or hover-over.

### PR DESCRIPTION
**Pull request by oliver-sanders**
Closes #1887 

If over six tasks fail between `update` calls then only the six most recent failures will be reported as 'new' warnings, the remainder will be passed over. Otherwise all failures will be shown when hovering over the error icon until dismissed (by clicking on the icon itself).

@benfitzpatrick Please review
@hjoliver Please review

### CODE REVIEW

**Comment by hjoliver** [comment]
Looks good, but:
  * Should we add "(Click to reset)" at the bottom of the error icon tooltip? 
  * If there are more than 6 new failures, can we add (e.g.) "And 7 more."
  * (I also noticed, "And N more." is only added for the top row, not per cycle point.)

**Comment by oliver-sanders** [comment]
@hjoliver 
- Yes, good idea.
- To generate an "And x more." message for the warning icon, the logic for filtering new/old warnings would have to be shifted into `suite_state` _(cannot do in `gscan` as `suite_state` only provides the last six tasks for each state)_, ok?
- Will implement.

**Comment by hjoliver** [comment]
@oliver-sanders - 2nd bullet point may not be worth the effort - what do you think?

**Comment by oliver-sanders** [comment]
@hjoliver I think bullet two would be a little difficult. You could do it by having gscan request warnings issued since a provided timestamp. This would require `suite_state` to keep a record of every failed task along with the time its failure was detected (we could housekeep after x hours).

If this sounds like a good improvement I'm happy to do it.

**Comment by hjoliver** [comment]
(My opinion: forget bullet two, or perhaps leave it for a follow-up issue).

**Comment by benfitzpatrick** [comment]
You could do it by recording the last 7 failed times, and then having `>6 failed tasks since last check`... or is that cheating?

**Comment by oliver-sanders** [comment]
Could get around the need to store a complete list of all failed tasks that way. This would make the `And n more.` message a little difficult as `n` is unknown.

**Comment by oliver-sanders** [comment]
Will implement as outlined in the last two comments in due course.

**Comment by oliver-sanders** [comment]
V2.0

**Comment by hjoliver** [comment]
Very nice.  Can you just add "(click the alert icon to reset it)" or similar, to the alert icon tooltip?  I don't think it's obvious.  (Same goes for the status bar alert icon actually).

**Comment by oliver-sanders** [comment]
Added "click to dismiss" to the alert icon tooltip.

**Comment by hjoliver** [comment]
Thanks.  That's me done, over to @benfitzpatrick

**Comment by benfitzpatrick** [comment]
Looks good, but I would hide the triangle when there have never been any failures.

**Comment by benfitzpatrick** [comment]
Otherwise good to go.

**Comment by oliver-sanders** [comment]
@benfitzpatrick Warning icon now hidden by default.

**Comment by hjoliver** [comment]
Thanks Oliver, very nice.

One final thought though - `submit-failed` should probably trigger this alerting mechanism too, no?  (It would probably be enough to simply group together both kinds of failed state and treat them as one).

**Comment by oliver-sanders** [comment]
Submit failed tasks aren't given a `summary['finished time']` attribute so were not marking it into the warnings list.

fb24c1e adds `finished time` and `finished time string` when a tasks state is changed to `TASK_STATUS_SUBMIT_FAILED`, is this appropriate?

**Comment by matthewrmshin** [comment]
May be worth doing a quick `git grep 'finished_time'`? If I remember correctly, `summary['finished_time']` may be used to calculate the run time of a task in the GUI. It is worth checking if the logic will continue to work correctly or not if this is added for a task in the submit failed state.

**Comment by oliver-sanders** [comment]
@matthewrmshin Does not appear to cause any problems with the T-finish logic in `gcylc`.

**Comment by hjoliver** [comment]
A couple of problems noticed:

 * If I try to run a suite that is already running, the "port file exists" error runs into trouble:
```
$ cylc run states
No handlers could be found for logger "err"
Traceback (most recent call last):
  File "/home/oliverh/cylc/cylc.git/bin/cylc-run", line 31, in <module>
    main(is_restart=False)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler_cli.py", line 71, in main
    scheduler.start()
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler.py", line 229, in start
    self._check_port_file_does_not_exist(self.suite)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/scheduler.py", line 357, in _check_port_file_does_not_exist
    "ERROR, port file exists: %s" % port_file_path)
cylc.scheduler.SchedulerError: 'ERROR, port file exists: /home/oliverh/.cylc/ports/states'
```

* Some messages seem to go to `log` and `err` without any priority (also on master, but we could fix it here).  On this branch they're also being prefixed by a tab character, which looks odd.  E.g. from running `examples/task-states/`:

```
2016-09-04T21:47:14Z ERROR - [bad_good.2012-08-09T00] -submission failed
2016-09-04T21:47:14Z CRITICAL - [m_x.2012-08-08T00] -(current:running)> Task job script received signal EXIT at 2016-09-04T21:47:12Z
2016-09-04T21:47:14Z CRITICAL - [m_x.2012-08-08T00] -(current:running)> failed at 2016-09-04T21:47:12Z
2016-09-04T21:47:18Z ERROR - [bad2.2012-08-09T00] -2016-09-04T21:47:18Z [job-submit cmd] (prepare job file)
	2016-09-04T21:47:18Z [job-submit ret_code] 1
	2016-09-04T21:47:18Z [job-submit err] No module named fail
```

**Comment by hjoliver** [comment]
Review 1 - all good now.

**Comment by benfitzpatrick** [comment]
Yep

**Pull request merged**
