### PR TITLE
Send job xtrace to a new log file.

### PR DESCRIPTION
**Pull request by hjoliver**
Use `BASH_XTRACEFD` to de-clutter debug mode job output by sending xtrace to a separate job log file, leaving job.out and job.err as normal.  @matthewrmshin - see what you think...

### CODE REVIEW

**Comment by hjoliver** [comment]
This causes some tests to fail; I'll fix them if others agree this is a good change.

**Comment by matthewrmshin** [comment]
Agree with the change. I am wondering if it may be better to call the file `job.xtrace` to make it clear that it is debugging information from xtrace?

**Comment by hjoliver** [comment]
> ... better to call the file job.xtrace ...

done.

**Comment by matthewrmshin** [comment]
@oliver-sanders please sanity check.

**Pull request merged**
