### PR TITLE
Suite logging std output if logging unavaliable

### PR DESCRIPTION
**Pull request by hjoliver**
Supercedes #1994 

@matthewrmshin & @oliver-sanders - please review and merge, and respond to this question: 
https://github.com/cylc/cylc/pull/1994#issuecomment-246867874

If we're good to go at your end, I can make the release immediately, tonight NZ time.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Looks good.

**Comment by oliver-sanders** [comment]
@hjoliver 

> are you saying that this PR fixes the newly found bug triggered by a Pyro error

- This PR fixes the logging issue with a Pyro error which i mentioned in #1994 
- It should also eliminate any other `No handler found for...` errors in the process.

> you're still suggesting there's a possibly better way (via LOG_IF_DEF system) for a future PR?

- This is that PR
- This essentially just renames `<LOG>_IF_DEF` to `<LOG>` (previously messages were logged using either `LOG`, `OUT`, `ERR` OR `LOG_IF_DEF`, `OUT_IF_DEF`, `ERR_IF_DEF` _[for cases where the suite logging has not been set up e.g. validate]_).
- Now all logged messages will print to stdout/err in the event that suite logging has not been set up

> so there are no other bugs due to the new logging changes that we're currently aware of

- Apart from the `No handler found for ...` errors, no

**Comment by oliver-sanders** [comment]
A consequence of this PR is that log messages can appear in stdout (if suite logging has not been set up for whatever reason).

This is the example with the Pryo error, note the log messages at the end:

```bash
$ cylc run hello_world
```

```
            ,_,                                                       
            | |           The Cylc Suite Engine [6.10.2-256-g5ca4]    
,_____,_, ,_| |_____,           Copyright (C) 2008-2016 NIWA          
| ,___| | | | | ,___|  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
| |___| |_| | | |___,  This program comes with ABSOLUTELY NO WARRANTY;
\_____\___, |_\_____|  see `cylc warranty`.  It is free software, you 
      ,___| |           are welcome to redistribute it under certain  
      \_____|                conditions; see `cylc conditions`.       
Traceback (most recent call last):
  File "/.../cylc.git/lib/cylc/scheduler.py", line 287, in start
    self._configure_pyro()
  File "/.../cylc.git/lib/cylc/scheduler.py", line 394, in _configure_pyro
    self.pyro = PyroDaemon(self.suite, self.suite_dir)
  File "/.../cylc.git/lib/cylc/network/pyro_daemon.py", line 52, in __init__
    cval.set_pphrase(RegistrationDB.load_passphrase_from_dir(suite_dir))
  File "/.../cylc.git/lib/cylc/registration.py", line 297, in load_passphrase_from_dir
    for i, line in enumerate(open(passphrase_file_name)):
IOError: [Errno 2] No such file or directory: '/.../hello_world/./passphrase'
2016-09-14T09:35:47+01 ERROR - error caught: cleaning up before exit
2016-09-14T09:35:47+01 INFO - Suite shutting down at 2016-09-14T09:35:47+01 - ERROR: [Errno 2] No such file or directory: '/.../hello_world/./passphrase'
2016-09-14T09:35:47+01 INFO - Suite shutting down at 2016-09-14T09:35:47+01 - ERROR: [Errno 2] No such file or directory: '/.../hello_world/./passphrase'
2016-09-14T09:35:47+01 DEBUG - Initializing process pool, size 4
2016-09-14T09:35:47+01 DEBUG - Terminating process pool
2016-09-14T09:35:47+01 DEBUG - Joining process pool
2016-09-14T09:35:47+01 INFO - DONE
```

**Comment by hjoliver** [comment]
@oliver-sanders - ok, thanks understood now, I think.  

> > so there are no other bugs due to the new logging changes that we're currently aware of

>   Apart from the No handler found for ... errors, no

You mean on current master, until this is merged, right?

If so, this is good to go as far as I'm concerned.

**Comment by oliver-sanders** [comment]
> You mean on current master, until this is merged, right?

Yes.

**Pull request merged**
