### PR TITLE
cylc gcylc: ignore suicide triggers as default

### PR DESCRIPTION
**Pull request by kaday**
This make graph mode more user friendly when there are lots of suicide triggers in a suites design.

### CODE REVIEW

**Comment by kaday** [comment]
@hjoliver are you happy with this change as reviewer 1?
@matthewrmshin review 2?

**Comment by matthewrmshin** [comment]
Looks OK 2.

**Comment by hjoliver** [comment]
Looks good 1.

**Comment by matthewrmshin** [comment]
Unfortunately, it looks like this change has broken `./tests/graphing/05-suicide-family.t`, and the default for `cylc graph` `Ignore Suicide` button now behaves in a very funny way.

**Comment by hjoliver** [comment]
Oops, sorry - it looked trivial so I didn't test very carefully...

**Comment by matthewrmshin** [comment]
> Oops, sorry - it looked trivial so I didn't test very carefully...

Ditto. It looked so innocent, that I did not think I needed to test it very carefully.

**Pull request merged**
