### PR TITLE
Fix and tidy the show command.

### PR DESCRIPTION
**Pull request by hjoliver**
The ```cylc-show``` command was slightly broken:
 * it failed for the suite-only case (no task argument)
 * it didn't exit with error status if a non-existent task name or instance was given
 * cycle point input was not standardized

And the output formatting was a bit crap (e.g. blank lines printed if the suite had no title or description).

### CODE REVIEW

**Comment by hjoliver** [comment]
(TODO: fix and add to the cylc-show tests)

**Comment by hjoliver** [comment]
@matthewrmshin - plz review (or reassign).

**Comment by matthewrmshin** [comment]
Tests under `tests/graph-equivalence/` are failing.

**Comment by matthewrmshin** [comment]
So is `tests/manual/00-reset-with-deps.t`.

**Pull request merged**
