### PR TITLE
Backport #2981

### PR DESCRIPTION
**Pull request by hjoliver**
Backport #2981 to 7.8.x

### CODE REVIEW

**Comment by hjoliver** [comment]
@kinow - I reckon one review will do for this.

**Comment by kinow** [comment]
One review enough?

**Comment by hjoliver** [comment]
Ha ha - too quick!

**Comment by kinow** [comment]
Approved and merged in under 1 minute! 🥇

**Comment by hjoliver** [comment]
Boom!

**Comment by kinow** [comment]
Does it need to go to `next-release` milestone? Or just #2981 there is enough?

**Pull request merged**
