### PR TITLE
Fixed back-compat for old clients with passphrase.

### LINKED ISSUE #1657: Back-compat with old cylc clients broken at 6.7.0
https://github.com/cylc/cylc/pull/1612 stopped the logging of old-client denials, but unintentionally it also denies cylc-6.5.0 and older clients from connecting when they have the suite passphrase.  (I guess I should have done a more careful review of this change :grimacing:!):

```
$ cylc run --hold --no-detach foo &
...
$ CYLC_VERSION=6.5.0 cylc scan

# from the daemon:
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/oliverh/.local/lib/python2.7/site-packages/Pyro/protocol.py", line 1126, in connectionHandler
    if self.getAdapter().handleConnection(conn, self):
  File "/home/oliverh/.local/lib/python2.7/site-packages/Pyro/protocol.py", line 840, in handleConnection
    (ok,reasonCode) = tcpserver.newConnValidator.acceptIdentification(tcpserver,conn,token,challenge)
  File "/home/oliverh/cylc/cylc.git/lib/cylc/network/connection_validator.py", line 97, in acceptIdentification
    connection.user = user
UnboundLocalError: local variable 'user' referenced before assignment
...
```

### PR DESCRIPTION
**Pull request by hjoliver**
Close #1657.

### CODE REVIEW

**Comment by hjoliver** [comment]
@benfitzpatrick - please review 1.
@matthewrmshin - please review 2 or assign.

**Comment by hjoliver** [comment]
Note that `tests/authentication/07-back-compat.t` always passes if run alone, but it often fails tests 8-9, 13 if I run all of `tests/authentication/` at once.

**Comment by hjoliver** [comment]
Fixed `tests/authentication/07-back-compat.t`.

**Comment by matthewrmshin** [comment]
Looks good 2.

**Comment by matthewrmshin** [comment]
@arjclark Do you think you can review this while @benfitzpatrick is away?

**Comment by arjclark** [comment]
@matthewrmshin - will do.

**Comment by arjclark** [comment]
Looks ok to me. Test battery working in my environment. I assume the new test catches the previous broken behaviour appropriately.

**Pull request merged**
