### PR TITLE
1283.run mode cmd line parsing

### LINKED ISSUE #1283: cylc run: -mode=simulation uses run
The correct syntax is `--mode=simulation`, but when `-mode=simulation` is used by accident, it does not fail or do nothing, it runs as `run`.

### PR DESCRIPTION
**Pull request by hjoliver**
Close #1283.

### CODE REVIEW

**Comment by hjoliver** [comment]
@kaday - please review.

Test battery passes, except for ```validate/26-fail-initial-greater-final.t``` which is also failing on master.

**Comment by hjoliver** [comment]
> except for validate/26-fail-initial-greater-final.t which ...

I've snuck in a fix for this (I guess I haven't run the tests on my non-UTC laptop for while...)

**Comment by kaday** [comment]
@hjoliver this look good to me. Test battery passes, works in my environment. It does not `run` the suite and gives a Illegal run mode error. However, is there any way in this issue or a new pull request can we make the error  slightly more user friendly? For example, suggest a `-` is missing?

**Comment by hjoliver** [comment]
@kaday - I see your point, but this is really a general parsing issue that applies to all command options: long option syntax is supposed to be preceded by two hyphens, not one, and the (Python standard library) option parser doesn't require a space after the short form.  So ```-mode=live``` parses as ```-m "ode=live"``` rather than ```--mode=live```. In principle we could check every illegal short option argument to see if it matches a long option starting with the same letter (but note it wouldn't even have to be the same option, since long and short options don't have to start with the same letter)... but I don't see any reason to single out this particular option from all the others used in cylc commands.

**Comment by kaday** [comment]
@hjoliver - agreed.

**Pull request merged**
