### PR TITLE
Fix tests/cylc-show/06: back port to [7.8.x]

### PR DESCRIPTION
**Pull request by matthewrmshin**
Flaky test fix back port, roughly based on 75e376ac43.

### CODE REVIEW

**Comment by kinow** [comment]
The current failure in Travis seems to indicate that cylc-show/06-prereqs-output failed. Was it supposed to work 100% of the times now? Or perhaps an issue when running along other tests?

image

**Comment by matthewrmshin** [comment]
It was much more stable in my environment, but Travis does not like something. I'll take a look tomorrow.

**Comment by kinow** [comment]
Thanks. These flaky tests and the 20+ minutes build time are quite annoying. I may have a look if I can help with them too later :+1:

**Comment by matthewrmshin** [comment]
Travis CI appears happy.

**Pull request merged**
