### PR TITLE
gscan: handle ctrl-c

### LINKED ISSUE #2195: gscan: ctrl-c
`cylc gscan` does not react very well with `ctrl-c` at the moment. Port scan is now done via child processes in a method calls initiated by the updater thread. We need to have a way for the main thread to catch SIGINT, then be able to tell the updater thread that it needs to kill any child processes.

### PR DESCRIPTION
**Pull request by matthewrmshin**
Fix #2195.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Not ready for review yet.

**Comment by matthewrmshin** [comment]
You should no longer see traceback.

**Comment by oliver-sanders** [comment]
Looks good. I can still get traceback (or worse) from terminating either `scan` or `gscan` within the first second of execution, this probably isn't worth worrying about though.

**Comment by matthewrmshin** [comment]
I am happy with some traceback, but not happy with worse (e.g. zombie processes, hang up, etc.)

**Pull request merged**
