### PR TITLE
Improve custom template variables logic

### PR DESCRIPTION
**Pull request by matthewrmshin**
Load from command line arguments at earliest.
Store variables in suite DB on suite start up.
Load previous variables on suite restart.
PEP8 goodness for `lib/parsec/*.py`.

Partially address #746.

### CODE REVIEW

**Comment by hjoliver** [comment]
@matthewrmshin - this looks good at first glance, but in what sense exactly does it only partially address #746?

**Comment by matthewrmshin** [comment]
I have not addressed the GUI aspect, i.e.:
* Provide a way for the GUI to obtain the custom template variables from the suite DB for relevant generated commands.
* Provide a way for the GUI to modify these variables.

**Comment by matthewrmshin** [comment]
@hjoliver @arjclark please review.

**Comment by matthewrmshin** [comment]
Branch re-based.

**Comment by arjclark** [comment]
Review 2 ok.

**Comment by hjoliver** [comment]
Review 2 good, but command documentation needs to be updated regarding persistence across restarts:
```
-s NAME=VALUE, --set=NAME=VALUE
                        Set the value of a Jinja2 template variable in the
                        suite definition. This option can be used multiple
                        times on the command line. WARNING: these settings do
                        not persist across suite restarts; they need to be set
                        again on the "cylc restart" command line.
  --set-file=FILE       Set the value of Jinja2 template variables in the
                        suite definition from a file containing NAME=VALUE
                        pairs (one per line). WARNING: these settings do not
                        persist across suite restarts; they need to be set
                        again on the "cylc restart" command line.
```

And we should probably have a mention in the CUG Jinja2 section too.

**Comment by matthewrmshin** [comment]
Docs updated.

**Pull request merged**
