### PR TITLE
cylc.gui.tailer: fix SSH zombie tail

### PR DESCRIPTION
**Pull request by matthewrmshin**
On signal to `ssh` client, a signal is sent to `sshd` on server.
However, `sshd` cannot send a signal to the `tail` command, because it
is not a terminal. This leaves the `tail` command in a zombie state.
Apparently, we can use `ssh -t` or `ssh -tt`, but that just causes the
command to hang for some reason, (which hangs the GUI as well). A quick
hack here is to do something like `tail --pid=$PPID`, so `tail` dies as
soon as `PPID` dies.

@hjoliver @arjclark please review.

### CODE REVIEW

**Comment by arjclark** [comment]
Review 2 - looks good to me. Seems to have fixed the problem I reported.

**Comment by hjoliver** [comment]
Review 1.  @matthewrmshin - I'm not sure I entirely understand this.  You didn't give a recipe for reproducing the problem.  It seems to happen only if a suite shuts down while a remote log is being tailed by the GUI - is that right?   Do you understand why it only happens in this circumstance?  (and then the remote tail process does not die, but it is not technically a "zombie" - i.e. not a defunct process).   I'll merge this because it does fix the above problem, but I'm still interested in the answers to these questions if you know them.

**Comment by matthewrmshin** [comment]
On using the drop down list box to switch between remote job logs, it kills SSH but SSHD does not kill the tail command, so you can end up with lots of tail commands left behind, disconnected from anything. Not a real zombie but orphaned children nonetheless.

**Comment by arjclark** [comment]
> you can end up with lots of tail commands left behind, disconnected from anything

I had 22 of them across our servers...

**Pull request merged**
