### PR TITLE
cylc gui: handle invalid utf-8 bytes in log files

### PR DESCRIPTION
**Pull request by benfitzpatrick**
If invalid utf-8 bytes are present in a job's standard out or err, the log file viewer in `cylc gui` will have a blank display and some stderr may be spit out like this from gtk:

```
GtkWarning: gtk_text_buffer_emit_insert: assertion `g_utf8_validate (text, len, NULL)' failed
  self.logbuffer.insert( self.logbuffer.get_end_iter(), line )
```

This change tests for corrupt stuff.

Invalid log files can be created by running e.g. `head /dev/urandom >>job.err` (although it is possible it might produce totally sensible text!). Our software that produced the garbage bytes had been killed by Slurm in an out-of-memory situation.

### CODE REVIEW

**Comment by hjoliver** [comment]
@benfitzpatrick - with your suggested test method, I get 10 warning dialogs rather than one.  Could it be an idle_add callback return value issue?

**Comment by benfitzpatrick** [comment]
It could be - that's odd, since I don't get that.

**Comment by hjoliver** [comment]
warning

I just took another quick look at this (on my Fedora 21 VM, laptop).  The number of warning dialogs always corresponds exactly to the number of lines printed by ```head``` (which is 10 by default).

I'll take a look at the code myself on Monday if the problem does not occur for you...

**Comment by hjoliver** [comment]
I think maybe you tested this on a remote task (all lines of output are passed at once to ```update_gui()```, but I tested on a local one (one line at a time, hence N warning dialogs).  We might need a separate decode test in each case.  Or somehow handle the two cases more consistently.

**Comment by benfitzpatrick** [comment]
Now changed - now it can only produce a warning at the first corrupt bit of text it finds.

**Comment by hjoliver** [comment]
That's got it.

**Pull request merged**
