### PR TITLE
Daemon now caches graph edges

### LINKED ISSUE #1525: gcylc: in graph mode CPU rockets
The CPU load increases from ~7 to 50-100% when a very large suite the gcylc graph mode is opened.

Investigated using a Ensemble4DVar 44 members suite in simulation mode.

### PR DESCRIPTION
**Pull request by benfitzpatrick**
This closes #1525.

Assigned to me for some thorough testing.

### CODE REVIEW

**Comment by benfitzpatrick** [comment]
@kaday, please test and review.

I think the important things are that the properties used in the id are the only ones that affect the graph (which I think is true) and that changing each property in that id forces a redraw.

**Comment by kaday** [comment]
Passes all the tests that I did in my environment to check that the CPU is not negatively influence by viewing the gcycl GUI in graph mode;
44 member ensemble global suite in simulation and dummy mode.
201 member ensemble global suite in simulation, but in dummy mode the GUI is unresponsive, but this is not a daemon issue but a desktop issue.
gsummary and gpanel still perform as expected.
Second review needed, @arjclark or @hjoliver please could you give this a check.

**Comment by hjoliver** [comment]
(note I'm on leave through Wednesday - school holidays - I will check in a
few times before then, but significant amounts of reviewing and testing
might not be possible)

**Comment by hjoliver** [comment]
Nice, works well.

**Pull request merged**
