### PR TITLE
cat-log --host=HOST tail mode now tidies up

### LINKED ISSUE #2664: cylc cat-log: do all remote processes die on exit?
ref: https://github.com/cylc/cylc/pull/2662#issuecomment-389280352

@matthewrmshin - best to delay the release a bit for this too, if there is a problem.  I'm taking a look myself, but I may not get time to complete the job today, and you'll need to check at your site anyway.

### PR DESCRIPTION
**Pull request by matthewrmshin**
It was not tidying up when its SSHD dies. Fix #2664.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
See also https://github.com/cylc/cylc/issues/2664#issuecomment-389451825

**Comment by matthewrmshin** [comment]
Python says *Availability: Unix*, which should be good enough for us:
* https://docs.python.org/2/library/os.html#os.setpgrp

The Python implementation and the Linux standard library implementation appear to be POSIX compliant.

**Comment by oliver-sanders** [comment]
It also says:

```
Call the system call setpgrp() or setpgrp(0, 0) depending on which version is implemented
```
From SETPGID(2):
```
       int setpgrp(void);                  /* System V version */
       int setpgrp(pid_t pid, pid_t pgid); /* BSD version */
```
Hopefully `setpgrp(0, 0)` is OK?

**Comment by matthewrmshin** [comment]
We are calling it via Python's standard library. I assume that Python will deal with the difference? (Optimism is a good thing, most of the time.)

**Pull request merged**
