### PR TITLE
suite stop logic improvement

### PR DESCRIPTION
**Pull request by matthewrmshin**
Internal refactor:
* Group stop logic towards the end of the main loop.
* Remove unnecessary attribute variables.
* Rename methods and variables for internal consistency.
* Generate reference log with filter (https://github.com/cylc/cylc/pull/1892#issuecomment-227383351).

Improve diagnostic:
* Improve orphaned tasks warnings - list orphaned tasks and their states.
* Improve labelling of shut down reasons.

Wait for event handlers to complete:
* On shut down due to task failures.
* On `cylc stop --now`.

Terminate immediately on `cylc stop --now --now`.

Partially address #1282. (Recording event handlers progress in suite DB and running left over event handlers on restart will be done in a separate PR.)

### CODE REVIEW

**Comment by matthewrmshin** [comment]
@hjoliver @arjclark This change is now good enough for review.

**Comment by hjoliver** [comment]
> Terminate immediately on `cylc stop --now --now`.

I'm not sure that's very intuitive.  What about something like `cylc stop --now --skip-events`?

**Comment by hjoliver** [comment]
Need a test for the single `--now` case?

**Comment by hjoliver** [comment]
Maybe put "Waiting for the command process pool to empty for shutdown" in the log too, as well as stdout?  (I noticed that this message doesn't appear in the terminal, with `--no-detach` until shutdown occurs).

**Comment by hjoliver** [comment]
Otherwise good.  (now `tests/hold-release/12-hold-then-retry.t` is proving flaky on TCI, but not just on this branch :grimacing:)

**Comment by matthewrmshin** [comment]
OK. I'll add a new test tomorrow. Today is holiday in the UK.

**Comment by matthewrmshin** [comment]
> Maybe put "Waiting for the command process pool to empty for shutdown" in the log too

OK.

> What about something like `cylc stop --now --skip-events`?

I have actually thought about this a bit on implementation. The advantages for overloading the `--now` option are:
* It is easier for users to only have to memorise `--now`. The double `--now` can easily be thought of as an emphasis.
* `--skip-events` is not quite right, because I think we still call the suite shutdown event handlers.
* The logic is easier to maintain - there is no need to check for `--now` when `--skip-events` is specified.

**Comment by matthewrmshin** [comment]
New tests added.

**Comment by hjoliver** [comment]
OK, I'm convinced.

Review 1 - good; over to @arjclark

**Comment by arjclark** [comment]
Looks OK to me. No problems from the test-battery in my environment.

**Pull request merged**
