### PR TITLE
modified images for documentation to match text

### LINKED ISSUE #2747: Mismatch between graph example text and graphics in user guide
There are a couple of mismatches between the image and text in the graph examples at 
http://cylc.github.io/cylc/html/multi/cug-htmlse9.html#9.3.3

For figs 21 and 22 the text says ```qux``` but image shows ```waz```.

For consistency with Fig 23, the image should probably be changed to ```qux``` rather than vice-versa.

### PR DESCRIPTION
**Pull request by wxtim**
Fix #2747 
I've not done one of these before, so I won't worry if you tell me that the format of the diagrams (which I created with Cylc Graph) is wrong.

### CODE REVIEW

**Comment by wxtim** [comment]
I've created new files using `cylc graph`. They look rather different to the existing ones, but are consistent with what the users will see.

**Comment by hjoliver** [comment]
> They look rather different to the existing ones, ...

It's only the node shape (box vs ellipse) that differs, isn't it?

**Comment by wxtim** [comment]
> > They look rather different to the existing ones, ...
> It's only the node shape (box vs ellipse) that differs, isn't it?
Yes

**Comment by matthewrmshin** [comment]
@hjoliver please review or reassign?

**Pull request merged**
