### PR TITLE
Replace instances of #!/usr/bin/env python with #!/usr/bin/env python2

### PR DESCRIPTION
**Pull request by ahuang11**
Method:

grep -rl "/usr/bin/env python" * -R | xargs sed -i 's#/usr/bin/env python#/usr/bin/env python2#g'

followed by this command

grep -rl "/usr/bin/env python22" * -R | xargs sed -i 's#/usr/bin/env python22#/usr/bin/env python2#g'

to clean up any existing python2 -> python22 -> python 2.

Referencing from this http://tarunlinux.blogspot.com/2014/02/linux-replace-string-in-multiple-files.html and that https://stackoverflow.com/questions/16790793/how-to-replace-strings-containing-slashes-with-sed

### CODE REVIEW

**Comment by hjoliver** [comment]
Thanks @ahuang11 

This change appears to be consistent with the advice in [PEP 394](https://www.python.org/dev/peps/pep-0394/).

I guess we just need to be confident that all our major uses do have a `python2` symlink on their system.  Hopefully this is standard.  I'll await comment from @cylc/core on this.

(Note also, port to Python 3 should be on the agenda next year).

**Comment by matthewrmshin** [comment]
Looks harmless.

Just to echo on @hjoliver - We have a clear roadmap to migrate to Python 3. The main blockers are the GUIs which are based on GTK2. We'll migrate the GUIs to be based on a newer technology first and then we'll move the remaining code base to Python 3. Hopefully, by the time we are able to do the migration, it will just be a straightforward style change exercise.

See also discussions on #1873 #1874.

**Comment by matthewrmshin** [comment]
I have moved forward the milestone of this PR. Although it is a big change, it should be harmless and is consistent with Python's advice.

**Comment by hjoliver** [comment]
Agreed.

**Pull request merged**
