### PR TITLE
Fix special task name check

### PR DESCRIPTION
**Pull request by hjoliver**
This fixes the task name validity check for special task configuration.

It also allows undefined task names in special task config lists, except in strict validation mode - so
you can temporarily comment tasks out of the graph without having to alter the ```[[special tasks]]``` section as well - which I think is consistent with allowing naked dummy tasks in non-strict mode.

@matthewrmshin - please review.

### CODE REVIEW

**Comment by matthewrmshin** [comment]
Please consider adding this test dcfc7b35938b0d825ce31a0510d7cdc40f4031e5. I am running the test battery in my environment now.

**Comment by hjoliver** [comment]
(I forgot to say, it was apparent this needed fixing because I couldn't use a hyphen in a clock-triggered task name).

**Comment by hjoliver** [comment]
(although I see you figured that out already - I'll take your test...)

**Comment by hjoliver** [comment]
New test added.

**Pull request merged**
