### PR TITLE
parameters: improve validation

### LINKED ISSUE #2359: Parameters with spaces cause incorrect expansion
Cylc will attempt to expand parameters with spaces, qe should probably fail suites in this case.

For instance the following example will produce the graph `task_1`, `2`.

```
[cylc]
    [[parameters]]
        foo = 1 2
[scheduling]
    [[dependencies]]
        graph = task<foo>
```
Also try `foo = "1 2", "3 4"`.

### PR DESCRIPTION
**Pull request by matthewrmshin**
String values must conform to the task name rule. Fix #2359 :bug:.
Detect and fail mixing int range and str values.
Multiple int range and int values OK.
Fix handling of trailing comments with internal hash chars in an unquoted string list.

### CODE REVIEW

**Comment by hjoliver** [comment]
This fails (on master too, allthough differently):
```
[cylc]
  [[parameters]]
      p = a, b #, c, d, e  # comment
...
```
validation:
```
$ cylc val err
Illegal parameter value: [cylc][parameters]p = a, b #, c, d, e  # comment: b #: bad value
```

**Comment by matthewrmshin** [comment]
Yes, I got something like this on master. I think the new message is touch more informative. I'll add a test for it as well.

```
2017-07-20T14:31:13+01 ERROR - foo_b:succeed #
'Illegal graph node: bar_b #'
```

**Comment by hjoliver** [comment]
Hang on - the new message is more informative, but still wrong - shouldn't the first `#` start the trailing comment, leaving `p = a, b # long comment with an internal hash character...`

**Comment by matthewrmshin** [comment]
OK. I can see what you mean, it looks like the logic that parses the setting value to a list is not returning the right thing. I'll see if I can correct it as part of this change.

**Comment by matthewrmshin** [comment]
Latest commit should handle the `p = a, b #, c, d, e  # comment` case correctly.

**Comment by matthewrmshin** [comment]
Latest change should catch the latest bad case. It also documents multiple integers + integer ranges.

**Pull request merged**
