### PR TITLE
Fix left-side suicide error message.

### LINKED ISSUE #1562: Unhelpful graph error message.
We don't allow triggering off a suicide event (`!foo => bar`), but the error message is:
```
% cylc val foo
!foo => bar
"'Illegal graph node: !foo'"
```

### PR DESCRIPTION
**Pull request by hjoliver**
Close #1562.

@arjclark - please review 1 (or reassign).

### CODE REVIEW

**Comment by hjoliver** [comment]
New error message for a suicide trigger on the left:
```
% cylc val foo
foo & (!bar | baz) => !waz & qux
'ERROR: suicide must be on the right of a trigger (!bar)'
```

**Comment by arjclark** [comment]
Looks good to me. Tested as working in my environment. Also tested with a simple:
```
graph = !foo => bar
```
@benfitzpatrick - please review 2.

**Comment by hjoliver** [comment]
branch updated

**Comment by hjoliver** [comment]
@benfitzpatrick - ditto https://github.com/cylc/cylc/pull/1567#issuecomment-130830794

**Comment by matthewrmshin** [comment]
@hjoliver Code looks good. Please add this test ac25ab6cbc269f45fd771dd3ce98831429d7360d (from HEAD of my branch of the same name) and merge.

**Comment by hjoliver** [comment]
Got it, thanks.

**Pull request merged**
