### PR TITLE
Tidied test reference logs.

### PR DESCRIPTION
**Pull request by hjoliver**
Addresses bullet point two of https://github.com/cylc/cylc/issues/830#issuecomment-226600596 - delete all the irrelevant lines from test reference logs.

@arjclark - a successful run of the test battery in your environment should be sufficient; it passes here.

### CODE REVIEW

**Comment by hjoliver** [comment]
For future reference:
```
sed -i '/triggered off\|Initial point\|Start point\|Final point/!d' $FILE
```

**Comment by arjclark** [comment]
As a thought, should the --reference-log option to cylc run be pruning these outputs anyway, or is that something that can't be handled easily as part of the existing code?

**Comment by arjclark** [comment]
Looks ok to me. Test battery passing in my environment with the exception of `./tests/job-submission/14-tidy-submits-of-prev-run-remote-host-with-shared-fs.t` which @matthewrmshin has promised to fix.

**Comment by matthewrmshin** [comment]
Already raised #1898 to fix `./tests/job-submission/14-tidy-submits-of-prev-run-remote-host-with-shared-fs.t`.

**Pull request merged**
