### PR TITLE
Selected back port to 7.6.x

### PR DESCRIPTION
**Pull request by matthewrmshin**
* #2606 Fix poll when job.status has no batch sys info
* #2604 Lowercase for shell bool vars
* #2603 Fix gui insert nested family
* #2602 gcylc: prevent negative job progress
* #2596 Fix ref by value of parameters with plus/minus
* #2592 Permit syntax errors with trigger edits
* #2588 Fix trigger --edit with host select
* #2586 Fix gcylc zero division error from task mean elapsed time
* #2585 Fix recovery of a failed host select command
* #2579 Fix gscan exception hook dialog closure incapacity
* #2574 Fix gscan host port range owner behaviour
* #2571 gcylc: fix tailer of remote job log

### CODE REVIEW

**Comment by matthewrmshin** [comment]
(Codacy is refusing to analyse this PR.)

**Comment by hjoliver** [comment]
Might as well add other bug fixes already merged, no?:

- #2604 ensure lowercase for shell booleans variable

**Comment by hjoliver** [comment]
(unless not practical due to conflicts and dependencies)

**Comment by matthewrmshin** [comment]
Will try on Monday.

**Comment by matthewrmshin** [comment]
Should now have the full set.

**Comment by hjoliver** [comment]
Great.  I can get the release out Thursday or sooner, if this PR is approved by Wednesday (Friday and Monday are holidays here - Easter)

**Pull request merged**
